apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/seerr
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: longhorn
    - name: cert-manager
  wait: true
  timeout: 5m
