apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secrets
    namespace: prowlarr
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:YT2SlnVACz2yFIrGorfosV9GK6EIExuwQ/6c3G666Sk=,iv:VL6CwWiGumKsjMdv5tm8ZbU+DTE0XnUy7Azyh9Rf8w8=,tag:RyZMma4AEXH+MWhNgQZwjA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWUV5M0dpK3RVQ2NiOEhI
            emhqOUZrYllLZEI4WGhDcFl4a0kxbkNYQWtNCmF6VXhLUUVUVU14elBPclJ3S3pR
            QWtuUDQyV09Cb0ZkSmh6RzFlaWhKcUEKLS0tIEhrQ3Y1OGg4dkowbUw4WU9ncFBN
            TUFhUHBsekg0YlE5MldxcVZLWHNNTG8KFbngSC1I6RO76S8cXGkRzC0mtMkD/C8/
            snIxWk4jWpInaniRivRz7MCdWgUVXkUV41D/n/3KBxhMLMGKQJSy8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T22:51:34Z"
    mac: ENC[AES256_GCM,data:qJmQQSBfWB/ayELyu2V1loetJ53tQ8UFABbEfXS9Oc4S2mAUKPPHNRE2gJNTJt6KVhvlsF6wgEnf03qp/qLJTxd6vkb+jmFqWeRP7XyXzDZ6Jq4SEN966JHGqJKJLDZkjd1TRibXPLXGXGX7MLNncL9YNIMEZmOZYDnBXNJjM9c=,iv:Ox/jsIZyjyvhwn7Hn3aKY0s5sTnLhh+/Q3c9zX4+LZg=,tag:oF5SVFDcig13rrzWxnRJ5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
