apiVersion: v1
kind: Secret
metadata:
    name: vpn-secrets
    namespace: prowlarr
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:EsRGrB5EBJ1x2vrUaWW85cDFJ+BeM+BdKt9AZmqmzePILtiUtP58XokoP0g=,iv:KvDOAEbAwo+vPmSrueL1MMJd8m/QPMkow6cVsgPYfhQ=,tag:7YIu+HC9/I3nNNXdaU8VsA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNS9TZStpTFUwdXdTdEZ2
            QzV6N1c2KzhhVWZJU2h5Y0Z3R3R4ckFON21vCjFsOUpySmNINFFta0tLN0tlemg5
            N1RQYkhtZXdhcHlIenhoazdPbHo2V2cKLS0tIERJREQ5OUpRcDc3WlBPZkRZZkRy
            UzNXbG9idVplMFR0cW9NVkhKdmlrazgKSOHMif4yN7hX7edL31uLSNyiAnLOT2tU
            V5SdCVVmAcnSkhqR9Ho/750y/q+RQWyo/tP5VJal0RD8S2ccytSYFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T15:11:42Z"
    mac: ENC[AES256_GCM,data:n42SiizpwjIMh3IH4ffWFV5j3WqFT1XahjNSkRv9uC8BmsXg/iYoMXKL3QDXp7EuPHKk1HV/fZ1WZeETJOqbfFsGs6xdiT6m4pCqcdlw82XWnmh3m0wK13S/BTu7mbZZNZK68gsyLf8+aw/TKBxl2XF8hOI2YGFaC/yyfyzd970=,iv:B88DVxvPY0yopGCR+vEZztxXD2S40pZa1Rz0MeATaFw=,tag:VLKLTyfWjtwiB/HD4Gb8zA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
