apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frigate-ingressroute
  namespace: frigate
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`frigate.home.coredev.uk`) && (PathPrefix(`/api`) || PathPrefix(`/vod`) || PathPrefix(`/clips`) || PathPrefix(`/recordings`))
      kind: Rule
      middlewares:
        - name: tinyauth-forwardauth
          namespace: tinyauth
        - name: frigate-headers
      services:
        - name: frigate
          port: 5000
    - match: Host(`frigate.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: tinyauth-forwardauth
          namespace: tinyauth
        - name: frigate-headers
      services:
        - name: frigate
          port: 5000
  tls:
    secretName: frigate-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: frigate-headers
  namespace: frigate
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      Strict-Transport-Security: "max-age=63072000"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frigate-tls
  namespace: frigate
spec:
  secretName: frigate-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - frigate.home.coredev.uk
