apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm.yaml
  - ingress.yaml
  - storage.yaml

configMapGenerator:
  - name: frigate-values
    namespace: flux-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
