apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: frigate-config
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - helm.yaml
  - ingress.yaml
  - storage.yaml
