apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-secrets
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:JRwKm1gyXFZnXwT/lKBsNjFi1bfD092/zNAX87xv7vtp6Bm5DJQJVZGP7Mo=,iv:wkywFI9zmbpLj6/sg9B7auLyZE901ZnJ+WLtcsJ1ky0=,tag:mzH9F9YOL6shirLwODNX3Q==,type:str]
sops:
  age:
    - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1E5cFA4MG9PczVyb1Zo
        bHRML3lDRWpjOXlDTDdCK1ZBMGI4Q01IRVRRCjNWbHVueWkrZjdXWGxVNEIyRGI2
        a1p0K0JiVit6TmlqNDg5V0hTaFFVbkEKLS0tIEZTbk5MWDd3UURHWktxa3djSEdl
        REl2ckI1NStnRk8xZVZmc2hVV1FjMHMK4RNuApg5kwWpiCB2uQqenTeIyDp/loYm
        DqiVhtTv9veGg5TctrQgc38B7IPZkWyJ3YXjojvvMrQvYbdPlEJOEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T02:14:55Z"
  mac: ENC[AES256_GCM,data:usrP1ZTDpzVdOMQiI8xl2WmoTIrXMKx8eJufzpHHMP5dKKXCpC+g3x9XBrb2fQWi4WZHUq4NrKRlOr0LRTKB8TSWg87eV24XVTI9fi84aP22P+0PljreLkWnkuX+MlAiDaP5bx8Br8gie6VQADeINcz2eOIMdVKnupFnnxin4yU=,iv:N9OsV03ny2bg2KOC00p/498Yjvk5kV4uUmi5LkrPUNE=,tag:T2pryPBEqubY5rQJsB6Wjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
