# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tinyauth
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.tinyauth.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tinyauth
  namespace: flux-system
  annotations:
    glance/name: "TinyAuth"
    glance/icon: "di:tinyauth"
    glance/url: "https://auth.home.coredev.uk"
    glance/description: "Forward Auth Middleware"
spec:
  interval: 30m
  chart:
    spec:
      chart: tinyauth
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: tinyauth
        namespace: flux-system
      interval: 12h
  targetNamespace: tinyauth
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: tinyauth-values
      valuesKey: values.yaml
