apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tinyauth-ingressroute
  namespace: tinyauth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.home.coredev.uk`)
      kind: Rule
      services:
        - name: tinyauth-tinyauth
          port: 80
  tls:
    secretName: tinyauth-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tinyauth-redirect
  namespace: tinyauth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: tinyauth-tinyauth
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: tinyauth 
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tinyauth-tls
  namespace: tinyauth
spec:
  secretName: tinyauth-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - auth.home.coredev.uk
