apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm.yaml
  - ingress.yaml
  - middleware.yaml

configMapGenerator:
  - name: tinyauth-values
    namespace: flux-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
