apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tinyauth-forwardauth
  namespace: tinyauth
spec:
  forwardAuth:
    address: http://tinyauth-tinyauth.tinyauth.svc.cluster.local/api/auth/traefik
    trustForwardHeader: true
    authResponseHeaders:
      - Remote-User
      - Remote-Groups
