apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cleanuparr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/cleanuparr
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: longhorn
  wait: true
  timeout: 5m
