apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:AwSL0Wo3NzfBfdE5tncZEFw1UnlveR9fuusq4klE7I9tnGr95RJbCgUPaAhfvPHr8O1OwOF46xcvqMVb36muS+Gc6/BLywHqVCEGzKBYme/GyPOm2gz4vbSH9j7M4NP0ffD1yQD1zyT111XKO/MlCPbQsj32Op6x5ZbH3qzODLRIK8pmEpVEL2exF/cUUD84Gmw0gb3GiVQqgJv4U2MGdesHgEot6h/b3n+uI2tT25W8gqvkOwcAPw==,iv:myoaf5+OEf0gtY5oHSGpmsnRkvxJmNEUJx6FFQ8+XTw=,tag:1X0PwblFSgisuSLOzYfawA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VjNvY3dkM0NJb0lNenBH
            Q1hKTFRNWWl0Y2pEWHN0Y20zQytBbS9zS2lBCkt1SXU1czgzY1pHbHB6RzdnN24v
            VTFHTTJJeVhJdGViRldyZnBLQ2NWdncKLS0tIDJFVXRldHc5ZlRFbFlZeEJRRk0r
            WmNUcFVFczhVWUo3dTBWYTFCYlNBajAKJuwg++MH7tN1MNEO+MXh6b3waBDsO14q
            JKerLSvIIf3lSsqHP35I0GSOOkfB2lMLqjOsGH6BFj9Q2Ct26AFptQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:40:25Z"
    mac: ENC[AES256_GCM,data:boEC6bHrOaZXTNiKDdVnxpJv6JO/rfI6daTf1T3w+7UPzmzCgwT6WuplDFOgEpQfBL/XesSciMZhNAGQ3Uwd5YsLP7U7ryZ9nZdPOrCHchFhZOW21cjQslud8f7Ig8f8WFR4izvL+YVbV6cZa2CybxyCjiDeUZKaYVzyEwrLPLE=,iv:ghB5iXR8O2+PP6twhMlPd9f/FmAg9X+mSuT5OUqR+V0=,tag:aJ/AG9fbak8SbAv/S2ebjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
