apiVersion: v1
kind: Secret
metadata:
    name: qui-oidc-secret
    namespace: qui
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:xU3f6R97RlkEG8foyW5l+LVeQyrYHBxbe9J7QGsF/nt13ltjBPDlQY9N41I=,iv:TtWr5nmwECMUTY9pA0vpRAhxf6vq0z1h+j7pWAdc5T8=,tag:P00Ced/MugKbRtUXqDILOg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWIvWkRrRlZsME5FM1NF
            R0RGaFB0L2YzOU1HNmdvUXpyYitTSTFLaFZJCnpqV3ZISmNtVlBZeXJ6dkJXVHZQ
            WjE2NWNYMDNsS3BjaEVDOUJEUjNXajgKLS0tIC9FSU00RmplMWRUWFlMb0xXRkMx
            UFMxeEpBM2dIWGc0bDVjclo0a3RFTGcKplctG71AmpqsQtejEWWSMEcJJ8YDI4uV
            7XLTQTKuDFfPOvVdY34CfoRlBsieh1yfScCz8SfzM2JXw6+pDaAHwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T16:42:56Z"
    mac: ENC[AES256_GCM,data:TnKqpfgUNeVH584IU8aKjrWkpLMyD0g0tpCGcn6dp13HYCCJ7iVsS4yGj+Tij1mPEyzmxFEj4fFXwDBo5wn1BDO4D/3tC90LpU6cHFz4vxuWb/XA/WUwRPO2YVsn7wZ4lEqVJ98F4Ml3zjHxDnGh6qAu07kcdYykjl4zSMe3aAw=,iv:qBd9xpmQJKPvDTG8TOIgD57imqcoznb0oHKb6Vyi/L8=,tag:IKnbssuz0YvksD/qxZhmAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
