apiVersion: v1
kind: Secret
metadata:
    name: qui-oidc-secret
    namespace: qui
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:mU4ylRMfqTCGox/y6bbQxGYciOItiSYT1i5F84xYq4Vh/2OB,iv:WTNkzCW27Wdqi/xJ79oId6cAUsOZ+RHl0uv1+gAzUIw=,tag:oQknjc+8weZHYeRgjt+vWg==,type:str]
    client-secret: ENC[AES256_GCM,data:ceZhqrrhJJLdVnc0I6d2RMA7NCGluMcXRdKxdNQ5/9M=,iv:q7WUeYJVez1O33usjl6wM1qNg7sEKBGt6eP/GBEJLfo=,tag:dkEy9nA1i3MEDTj4NBoPuw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1E5cFA4MG9PczVyb1Zo
            bHRML3lDRWpjOXlDTDdCK1ZBMGI4Q01IRVRRCjNWbHVueWkrZjdXWGxVNEIyRGI2
            a1p0K0JiVit6TmlqNDg5V0hTaFFVbkEKLS0tIEZTbk5MWDd3UURHWktxa3djSEdl
            REl2ckI1NStnRk8xZVZmc2hVV1FjMHMK4RNuApg5kwWpiCB2uQqenTeIyDp/loYm
            DqiVhtTv9veGg5TctrQgc38B7IPZkWyJ3YXjojvvMrQvYbdPlEJOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T03:13:35Z"
    mac: ENC[AES256_GCM,data:eghhkyOiMHXJZr7/vyCKCUz2i1q3YJYhF274SSveMUbi1bIl0bImSwUmZzBkw88ypt4mGSs0CUHULJ/SV3qVqIV/DpK9GGx4mwCrNx8tTROxdFDpoBDah1jm3LIuXPUjR9CO45XS6rKeh/QQxsyBRavYZFf3210pIAWuh0TKn84=,iv:vouufR8IHLAr5M90KnYYeaV9V9Jab7nWP6bfQV3x6J0=,tag:iZRPMhnX4Z7ykphTpVmZ0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
