apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc-secret
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:BLiiMni6bpK9ahfcZdIO6RWxh+8WSJCE2Tp9CQIyLFTlCfGRzsEURdzKkqStH5ajbRpnUA8oVVf63KFmfw7JTw==,iv:yqpkpF552BPeVwh0r0ju1oWa/6LFLc9RLdF3bRc5sOI=,tag:OZMT0tixKYNg7LBinjo2Gg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbmlJUVY5T3d5L011VTRN
            Z0R3S215ZG11RC93bEVrdmgrRmRCbStSS2lnCkRXbmxHamVValRhVlkyQng0b1k0
            L1BIWHV0TmltMWhzcHF1ZEZHZmRuV1UKLS0tIEk0bU84dFNXZ1UwakdJck5oMkkw
            UzUyU0ZKc3FtNUsrWXNOcG1rRDlsTWsKSF2kQigLBxKepVdJaa68Nyy7L/IHn4U6
            Gp76ecUw5nSD2l+AQuVAkcTmbjcQLfSKiWhJzFmhqJCcFZY/lG5OSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T19:36:15Z"
    mac: ENC[AES256_GCM,data:KXYpempvaoGCXQfATLNHy5KZgQg/DzuG3T0mxLscJTXLcUSD0xBA2AltNLfvIWBwQ9GN//OA4CBi1ywT0EvTbnZm/z0MaEuDjmCjuavhVP4kkLsdPDSmklSnvV/N8mUxGeikmtaiGgXdkuwhiRuj6gGkyNgpHu+9BFXBJx6Ld4s=,iv:S9NCsZU2I469DvDT9LVnBUWHQ+4C/Nl72Ibm7YvofHo=,tag:mPa8MG0nNC7aA7+8e+wQFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
