apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    GRAFANA_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:YU9Ln4ACchDXIpdlmqf2h6g1KM7JIUND6c5wJKQVE+lCh+A04czC5ALmx+ksDa62/TuRea/aqAW8SPGbgwd0ow==,iv:w286dyyVtTYYU5XEPEybT2H72BVqEXPD1QNVfzQX+lU=,tag:v82HryvXtdRhqGSvYSMI1Q==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZkkzYjA5ckJ3bDd6c1VS
            RVdSa1ZzWDAvK2FPNVJOcW1zSjZBbVByRGowCjM4aldBRDVaeE5BNzgwUlNsU2xN
            eHB3d3pEK2FmcldQTmJBQ2QzZ3pxeG8KLS0tIFVGeG45anpFU2FxKzdGaWtpamRD
            TFRNK2M1Z1BxMWFmUUtvTzgvRXhGOWMK/7Hqal6Ozo+FnsEYptRsM4gY250ztM6q
            MEZr+9N0Prbr3EA9tXeBgkVCJ1FdvMxU3hldfO6H3Ji6jtuS0SloDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T20:48:44Z"
    mac: ENC[AES256_GCM,data:SaADo2JI18WIRGewgheJuYZloJH4jlQ2uaJHMNLl1ckozRYOe/mh8tnA/vMY/ZqisQFn77b5iCaMC+nlNqlNeDyyIvwG6KskE+TthixhYMFQ00zrr37hpW3qsPR4poYQIrXbzhkoQ/nDpkM8t/Sz3O+yWwj3yIBYTYKbK0AaESo=,iv:4igjHquUKPv4QRhlJ6KJaVavKcNJUakP4vkWw6oD3ts=,tag:SLL/BR7LLwXjKF2GMaUO1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
