apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:VKGjhZhdIV9JfFejlVnKTrfq+3Su63IxtaiHHbfigZY=,iv:yWCqHEPyB5oaihNWLhxb4gAAZaYqvovM7W8SdpFUH3Y=,tag:wpsNxJXMbXJkfojKuOBWMQ==,type:str]
    client-id: ENC[AES256_GCM,data:ljLlFQ7VBcSB02are46HN+Uk5G14W3qvI7hHqnrN4ixTKKXg,iv:9xmuRkyWbLMvv0++G+plV4Qut0gSe0AAEg4T0v8SPio=,tag:rOL0Mbk87ZEN2dP7i9x7kg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZkkzYjA5ckJ3bDd6c1VS
            RVdSa1ZzWDAvK2FPNVJOcW1zSjZBbVByRGowCjM4aldBRDVaeE5BNzgwUlNsU2xN
            eHB3d3pEK2FmcldQTmJBQ2QzZ3pxeG8KLS0tIFVGeG45anpFU2FxKzdGaWtpamRD
            TFRNK2M1Z1BxMWFmUUtvTzgvRXhGOWMK/7Hqal6Ozo+FnsEYptRsM4gY250ztM6q
            MEZr+9N0Prbr3EA9tXeBgkVCJ1FdvMxU3hldfO6H3Ji6jtuS0SloDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T03:30:10Z"
    mac: ENC[AES256_GCM,data:wTx3ItpZFrmg1X0oHUCHsM8BbU+3u5fKFVWJ8DruAkwMDiEfSe2looPEbX6JSYzZgEJKOVM7EBKMfFVAfsyzpfej8jfFJGKF16DINM47ZyMwj0Qd7GRqJgVTApd4N6mJ/ksIA9mRxD+/K/DHz2io1wxj7VkFZg7G08PDpdH7sfQ=,iv:6aMchZPOpZk1qcrFoOvMKUxWpvNVzDCBst4w5LVOvzM=,tag:FjELNsiNALh3Gy+dSRCBnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
