apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: jellyfin
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:4URCCGZYbS2j4AhixvqgFd3yEMJprveYrpwU+q9FwGVBRDHPQrPbmCXtX3s=,iv:NA1xE8Oz/8AaHKFW7ehTJZDec5FmdWGBnxzyQrwrrN4=,tag:aWmgcWOJsMpi5h9JGusZTg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d2VYV3dIL2laUFV6YnQ0
            TUVqK29xTEFXdzZPTjVuZGdKSVJHdGpwZjJBCm1qZTVubVVySW5IeTFpRzFhNEFE
            ci85Q2RJVGhURExISkdVQnB0SWdYaDgKLS0tIDErR2svUnZOanZhdUxWZElEbUdq
            RkVKSDl4VjJQYm9BK0l1b0FRWDJXWU0KC5s+XJB+kZTCz8R9rtqQUB748fpuAF0J
            SenfnGOAy2gYIP2GIlBz/YC4W+yV3XfDJtyM3/N/ZAyWOcd1Zy2Zvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T04:09:41Z"
    mac: ENC[AES256_GCM,data:rHMc6nW1wfJjsVoNeQmm+MgXtukc9D/Yg1PFiA3xKF4xi/UeYA4UWWFy3KwNFPGu+eyypP+WbocXjGsdm6NJNEPHzKZVtrGiN70rdf0v9krgW7Lm/2GTtsERuayubi/E5b4pwnKAt2VNP+zCgNhP2h/kCwsCMtGC4HWxVfF4lms=,iv:fO8IjRYz/aU12uReHn0G5g7C1DB2HvTJ4kIQid8YuqI=,tag:pPoYq51HPcWLhn9zJ2yREA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
