apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-ingressroute
  namespace: qbittorrent
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.home.coredev.uk`)
      kind: Rule
      services:
        - name: flood
          port: 3000
  tls:
    secretName: qbittorrent-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-redirect
  namespace: qbittorrent
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`qbittorrent.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: flood
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: qbittorrent
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-tls
  namespace: qbittorrent
spec:
  secretName: qbittorrent-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.home.coredev.uk
