apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secrets
    namespace: sabnzbd
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:z61JLlzV96Bx/195k4GSiEgIeIUQ3W0hk+LsFIsm8PA=,iv:IT2n4yd4ormy5sXJ6Yh13EIMnIFR+OG1fv8SyJo2hUs=,tag:oPKyJCF2vXYww13x7Rl2yg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RS9PMHRSSWgwdlliVzlt
            OGwva09tRzNuYm12ZVk4YlVZbzFISHJvc2pJClQxK3JYMWF1ZndwZDI0NnFpSHl6
            OVg2Z2VzZEdVUUtLb1NkTWJLcEJ5VDgKLS0tIC9zMDlkR3MycDNaRi9QSmRpaWFQ
            RWVCaTV4K002cGR6eGpMOThIdXFFMWcKGXD4W0CaeudFVR63itga8nEuDGhU2dmw
            fhdrnQR9xck/cGqKr+WIT0ppGPuxM9cBOBFQCBM8tOFKO+ay/UuChA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T22:51:34Z"
    mac: ENC[AES256_GCM,data:n3Jw/x7h7EQaahFekMp8ezRd6TvBCjtnrsmNBuLJBhFeMmtqKnvMSz6WBgNn0amRcTxMbkeCj0hkdatAkNVDp4i5PlakAeYZ7StRwoJyQPHqv7OkaJDD3tzP5973LIzGk036urDVoabIiIulgZC8QHKBtVoZ35UiKapPXWXj900=,iv:PgfKVmWRgw5rCiDO8l5T4kGYeuKvAtMJeHAuxfKiSYY=,tag:W2urptXpeIts+Y2JVeSGpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
