apiVersion: v1
kind: Secret
metadata:
    name: vpn-config
    namespace: sabnzbd
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:vwmKEWze8LihBIb+R0DkRMV2jlv91/ZV1Ma7jUOz4tlZAbfJSzWjDanHnTA=,iv:B/M6GfhBCHzkQKOm9+dUHeEmanwdcCnwEjnNPSmVoBg=,tag:JOhqTkpffvO1sTUagaWj+A==,type:str]
    proton-email: ENC[AES256_GCM,data:83JxqhAFRuqEmhPoYiQqpuzV2OXbi4BQtQ==,iv:NY1pud1q1MG6AHR/Kz1dtTuh2z93VVmQc8lXxwKvxsg=,tag:DvY9lHnJbn93WppwZOuKSw==,type:str]
    proton-password: ENC[AES256_GCM,data:r1T8Qr9NYzuSpBy3lYf5mCllxiduv2TNChpeydTpmGw=,iv:R3ONDI8Mo3hHYUZEVcMxOoMMMdg3AQSWyi6CC/r0e8o=,tag:PB9KHhUma3+zcEqymjjPcw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdkdZbGQ1UTBEa0poaExK
            TktNdEdvNEw3NEdmTFdmbElocWgvQTZNWUUwCkZkTUFqZkNvL0oxY1hJMlVFYWNF
            OU9zZWRmd1V5a1NrdkFmQTB1eTJFQkUKLS0tIGU3RkZKd3U5SUFaY2tFNlRIbTJU
            T3U0ZnoyRjNNOEVCMUMraUtLTGE2cWcKW7gQ4EHnGWop/E8Oib8QBRSTfSfrtsO5
            WaxRmNc5wi/N22DSYYVakMjC6qT26SoEleq29thZUxzaxEuDQoeGCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:40:30Z"
    mac: ENC[AES256_GCM,data:FfFDwwWCbnpWxDyw5AuDGnDa6Aw7TrXCjk65EKOjoJw4UabkORDtldRp+jQIrp7w00o0ATviv3fgiBqReMGa7vu5GdoVRAVlM8IP8Z/FYkoXLdBB3fm8elbJMUw6VFy6uK+V5Nt1vMECEJKydjV6/4ASiFOEGJq6yE8Xzn9KK4Y=,iv:Z+1bVgMW7WkoEnWp+DvsZ/mev1AoxB2Xi9CK1c1qz7w=,tag:d061iHONirzNAOhmn4w1eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
