apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: sonarr
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:2p6Bs0xvb1e2YAosyp7E3kWg/P3K0vg+mjLUI5bLW/8=,iv:P2Kouh4xUZ8XkjxIXc36TVRMoSyrlxW2kqv3rKiQofM=,tag:gZl3gcBLuWgkmmxmxifDYw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNlM1VXZ5dG9DbXNBUmt2
            RnREdlZBUGlmb0NhcmlWc01DSmdEYlZLSkVRCkh0ZHErUWZzbVMvSkoxSjJlT2Ru
            Rkx0RGVHRnNUdk9IYWdFR1ZseXlRTEkKLS0tIGY0ZGVVKzZlR2FySWwwQno1WDJC
            NGEvMnVXZTYvcTU4Y054T3hTNlIwamsKwDD3qn5E6SycTqw8jbHqYq8GCHUXucfV
            pZv4iG/KODT4zxusZ6BZChLwssAKA4wD82DzC1K15jgzlVECbyoKfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T22:51:34Z"
    mac: ENC[AES256_GCM,data:HxzOHt6nrgZiH/9fbO52BsFKUaVViejtemqYCRdDPkYPgKgKz1Sdk23qAPYpKgP+9hkoORp+vVUiumiVZuoyII2mlTSPLjkRzuWDaBep86u7TBaFObhUxyIUQOpkRdGav0wPSkg22iG7KsMu3s4QHdkhMhS4GMkSTp/pP4zaduk=,iv:vKQACFPsM7jS5aa4vxuhT2w24VWu7kN3qPafFktNgO0=,tag:CxHwAxnYu/b948Kf7LjTfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
