apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: radarr
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:TVnrxFAhoOlGgfHsmz1z6R9e0bhASs4KyUrg82I64T4=,iv:yl9G0q2RJW2CtA0ZpcLd95bnIkG+feNxaWYDejr6Dzw=,tag:wq1bjioUo9BNazIR+0/Q5w==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOUFqT0Y1ZitBS3JmaGJq
            RERPbExQdlpvZ3BtWFZ3YnJMdHR2UGRQK3lzCml6RDBva0E1Mkt3cW1MS2k5cjQ4
            MUxsclRRRUw4aHY4MDh5NlU3d3FVU1kKLS0tIEVhWlg3NFoyYW9mSU5UanpJMzNt
            eEJuNmRyUS8rRkg0anBPVmgrdTVaakkKKWQVutftw5rigRpFs7SMtr6ccoTCSx5W
            Qg8Mj8LwFyFDb5rS65EUyzNxSEsVi8rsd0wbtb3R86ON2o7ofenyLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T22:51:34Z"
    mac: ENC[AES256_GCM,data:qCxJ/vu097K8/wCZb0eADg7PFyXRANN6loiuclDaG5hsPnqCC+ZnATIWmbwS/RXf62+JGYvRoo6+eLO7tM8phw8XtnsuplFkYTAdmZfl13D96xg6giKHTrvTi1/qu7r1xqiPRaQoE3itqT3GkIf0/9diOb/pV50NXOf0ndqZVqs=,iv:PnYcTp3cRaw4Ks+FKkz8HFIJPvRkwSx3EtPTHxPn24U=,tag:J0VdXULdtxfBNZWWnp/l2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
