apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-secrets
    namespace: flux-system
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:KSU9+Hk2pPppR2HQmx8ZFkReVO/+IbU0UWrecZAyAhhWIJbevplGvTB9h+TDTXGKxC0zlvJ9BMtPpsm3kSpxj4+XgumkXg9g+Jh11p93eEMNUGca3QzoOmvheYEE4L8yHXQ+r7/VBfSpIMNNcqXiAD2CF3X4TiVoXfVO1q0+f4SJesUKu2Q6vuJExynQH7w+lupi+aPm7MmqfSg=,iv:UW3E259oLbMHC14XcOUOYh8FSi/XogxyUHCI5v0ECTw=,tag:g16hbpzY8zFaP5pT2RGTOA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneFBuVmFJR091blJGb1Jr
            aDB6VFd6TzBrSHVjd0grRHhBU2sxSU9HVkhrCml4WExmV0g4V3dkaUFxU2RpbWgr
            V2ZtRVdCV0t0eVdySm91WEtVTERnVkUKLS0tIDB3Y2ltUytvdGpnY3lLemQ4bCsv
            SjlKd0hqNlFOZCtvNHdsMGtnMFJSaXMKJI62h/0igLIvfNC3qV+W0ns7x03aUHir
            wKIVFCVnM0kHM+Kywayxfcpxp8b1tSJKU0b/yhUqydvS5NKBHfVXtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T14:38:46Z"
    mac: ENC[AES256_GCM,data:Rkhxs4EOkaFJlSXrqOEN0gYS3EISnE6bKrYVGqgL+3s8gZPSpurWkAVRXmXfXkLseoGUaXh9fE8pKDtHidhvFQ2spEZLvfCEcThoBhMQhCGLPUCHA+A1+M/0GquR+l8c6UjHxktStL2P2kvkPJeh5H8Dao54Wl5aEtYLa4KyLFQ=,iv:XTEnZm52M8do18HUGJTn0VQfp+mpgPKD65OzB1s8hm0=,tag:/LbVnGpb7TeEKGudgs+XFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
