apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-oauth-credentials
    namespace: tinyauth
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:ym6ISNhaxYrlgxlrP15nfixl6/+432vmRlg9Hn0vl2Faep2c,iv:PRkGnKzJ7HvYTblID7ZofiTqB7YytdX+R3pTk8hZ7D4=,tag:b2GOoOhK3EmLCZhY+YjPLg==,type:str]
    client-secret: ENC[AES256_GCM,data:X953WcXOOXsYMz8lrjy3wy4M90EJ5Zw9Y5uyZPitqGQ=,iv:eTmImIDIOjJJVo4c5gJ5pAtxIhCcFxeLgJdWwDdR5cI=,tag:SSQCfuFoWPfZcLNUa9gyhw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOK3NOVXorc0hWUFJyWG53
            SUY2R2w3MThadEtnMVRVMlNvb3huYTBJQkJNCmI0eE4yR0pISXVIM1NqRXkvTktJ
            VVVMSGVTUm5GbU9WY0VZTEF1SjAxRXcKLS0tIGRYSk9TMXJyYkptRVBEanZxbHdV
            Q2IwQ0R2VGtkUUNDK3pIdFJ1a3lSVzAKZouI8WYEOAH++1pT9RX/jhCSFtGNteF5
            /4lrq8m/srqYrRnn6oBv86Gr39zMDIoP3D9nlpbZKA5iZcZbDfzH0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T14:55:52Z"
    mac: ENC[AES256_GCM,data:dq5kPSfdKJ82mMRTehgE414gvHxowp21rDv2Bkwjy+a2GzGbyx3z6nYfVoro+/ZFNJUZV+WwI78Cw6zMHxtfR+WeMVgHxktTbPlyk2RyB0OQjbva2/N+r4sXLyYrynbTlgkBeXkPt78MRptLLBAKrg7TqJgioGA/UVlyDW1hNN4=,iv:KqGNxAQU4FIfZ3M8pdkYY3z0OF4TFViI+hWBZ1rrp5c=,tag:z575JAMRdi7ACLpboGa3uQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
