apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance-ingressroute
  namespace: glance
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`glance.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: authelia-forwardauth
          namespace: authelia
      services:
        - name: glance
          port: 8080
  tls:
    secretName: glance-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: glance-redirect
  namespace: glance
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`glance.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: glance
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: glance
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: glance-tls
  namespace: glance
spec:
  secretName: glance-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - glance.home.coredev.uk
