# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glance

resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - rbac.yaml

configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=config.yaml
