apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glance

resources:
  - ingress.yaml
  - deployment.yaml
  - pod-monitoring.yaml

configMapGenerator:
  - name: glance-config
    files:
      - glance.yml=config.yaml
