apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd-ingressroute
  namespace: sabnzbd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sabnzbd.home.coredev.uk`)
      kind: Rule
      services:
        - name: sabnzbd
          port: 8080
  tls:
    secretName: sabnzbd-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sabnzbd-redirect
  namespace: sabnzbd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sabnzbd.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: sabnzbd
          port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: sabnzbd
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd-tls
  namespace: sabnzbd
spec:
  secretName: sabnzbd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sabnzbd.home.coredev.uk
