apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sabnzbd

resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
  - ingress.yaml
  - storage.yaml
  - exporter.yaml
