apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingressroute
  namespace: prowlarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(\`prowlarr.home.coredev.uk\`)
      kind: Rule
      services:
        - name: prowlarr
          port: 9696
  tls:
    secretName: prowlarr-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-redirect
  namespace: prowlarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(\`prowlarr.home.coredev.uk\`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: prowlarr
          port: 9696
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: prowlarr
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-tls
  namespace: prowlarr
spec:
  secretName: prowlarr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.home.coredev.uk
