apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: pihole
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:yK0tD8lVTpDRnitUtKQ=,iv:HKYwvwWJPjca1C+gjgK7reeXLyJsV6c5eedz6pgytKA=,tag:+ODoEQeMbUVK4BEGijQhvw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbVVCdUEwbWUxU1k0S2RN
            QStUK3dvNXhJWUVlaG44VjFoYkFDamdXRkdFCkw5dGJJSDI3U042SVNGd2Z3OGti
            QVhqcGtGQlR0ZmZGU2h4Y2h6M29tczgKLS0tIEQ1UFJQekJINEZ6VWkyOXZCdGVU
            SmtFczA3QjBlTDdWVnVQenJqTE5YV2MKK02DsN14SoWDhnVtSG34oEUoVL2CjiT+
            mv3uhn9UGHlR2wjP4Rdzg7n0TVND5nzUAB6QeQ4QE5HSJGfo+k1wtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:40:28Z"
    mac: ENC[AES256_GCM,data:9cuKMuLGhXWdKWY87Z9Ar/M/oxTuWK1XFuxmfAtJUKjuPo0I46727Ex9uYq1BywJ9vwi2uXYQHIzuVHl3mI62pdyumyo7wtRVYtw37b3yGA065zsc7rtYgaSOyg98v+wamww+sWQJWpFWGCE3awbmx3hdzR+ESSlQ7CN67NnTm0=,iv:PcenGQW7x0KnerGX00OVg3l/ebM0i1+y3FPp8wZLVyA=,tag:XAb25jdSJncizD8JxnISMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
