apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge-ingressroute
  namespace: homebridge
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homebridge.home.coredev.uk`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: homebridge
          port: 8581
    - match: Host(`homebridge.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: tinyauth-forwardauth
          namespace: tinyauth
      services:
        - name: homebridge
          port: 8581
  tls:
    secretName: homebridge-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge-redirect
  namespace: homebridge
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homebridge.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: homebridge
          port: 8581
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: homebridge
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homebridge-tls
  namespace: homebridge
spec:
  secretName: homebridge-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - homebridge.home.coredev.uk
