apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: frigate
type: Opaque
stringData:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:saADTlmsRo4=,iv:6IjUcGhjfETGDxITUIoTkBYI0CeUVqfkPOLqLouVlTM=,tag:CBM7G+yLqp4FnR15vD5qeA==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:Ef/HOg8lUhK+,iv:iy5dd8PR6bTUiYY2e6ovDJVpaLMgZHl8HEo2BLRT3bE=,tag:vNsJNDrpsJojQiE/StsBYw==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:sHieb0HPv2WHaBEurOA=,iv:DVmkbwh4w7nRoMt6DMU/JzCOYOhswnYS2vKFWdfWoHM=,tag:KRniyu/ZikhDlCoXe9DYgg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SVZmSkZnZjlaQmg5WXJ4
            bFk5bExjQlJyenQ1aWg0bEtpMWVhSWdqM3lBCmpGMGRIdDFVQ1BQbGRvSlNFbWx4
            bURPYnovN0pnTE9YTGdDeDV5NVhuRTQKLS0tIDNBL2xGT1hDb0x3djZLNDgwY3pj
            TFM4SDJ2alV0THJSWU9Zc0hvTmhySk0KnKJHcsVVrmFoWiKBsyjDysFtyC+sVRBN
            lSmLXThX6Bg+AYhGuSAjYd27WsNdqXifyF2iRYFOO3e/R47Vt37H7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T03:27:35Z"
    mac: ENC[AES256_GCM,data:cyJs8TEEewm6CZjUlG+KfSBn8LvuMk/YqWAImhaQo/1HCnXyOUEvhvjnaop8c8YwYaXs44M5X69DsZ8NGoDQx9VB4M8o3s9em2W8dITewj99/K2AgoIH6tHxSpdYihDudipPydIojLLL8oXDA8aMvFmX7SybYcBtzPm9DxNqhV4=,iv:ruGiYMFvbFJEwVh2hNhKaP5rn5tOcSEpScj76lJKSiU=,tag:BF8qIUvBqwtoP3oXSmOArg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
