apiVersion: v1
kind: Secret
metadata:
  name: frigate-secrets
  namespace: frigate
type: Opaque
stringData:
  FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:vjufpPzbleQ/GPcBvgw=,iv:+z8jGf2rTCSUK5ahXIlr4axsrHlAhLYjTisBHE/Rgtc=,tag:2GYaLBdqh9izX1rcpSadSg==,type:str]
  FRIGATE_RTSP_USER: ENC[AES256_GCM,data:TmAroog2sUk=,iv:7YZcLIs14o52zTYD7MvZ/GBC3AvYKs4neLyLghjUh2E=,tag:KwYHYpZgpbqbjc3ts/ge3w==,type:str]
  FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:EQI8VE9Cv1WS,iv:bTILBF0RkPkOrldVS6qnOF/mJ955EZ0TR1NyT8cciNI=,tag:Qe8DFse1qAaqdBgppMBK7Q==,type:str]
sops:
  age:
    - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNXVpbzVSN2h3eFI4NUkr
        UURTcWMyUXNHM1Y3blc3dnBpKy9OU2lFdlU0Cm02YXQyaWtURkcxMjhQcnFRKzBC
        NVhuM0MxaGNBZ0pWdm9LbElUU1NiVVEKLS0tIEpLME5mRWREVmR5cDNnTnFjWElL
        TzNZV0M4ZmpqK2t0d1Axa2NUbEI5cDQKm+R77mBk/zqbXvGf0iLX4FhAlVX8jM3o
        qr/ojkIuremEgpIivQsUT/8+bZOpj15mo+CFj52et9+ZbFkk+HtNzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T12:40:25Z"
  mac: ENC[AES256_GCM,data:5HUCuNUXf3GrFzg65sIBrbkj8MdG9c40b4sgqrG6dhuBg6KbOAHk5Hg5NxausqLVq3eMgd0WvUQsPqOl4ZPyr2UqlH0DXYTkPmzXOA3L1fMis9bzYUK87FeMKb7WVlaoPDeyeye1tZLk5ZCVAqKV7EZOQQSvFdwYTV7mrJTfgW0=,iv:zCxtbt+9LaJUecqySkKwvk+ETQ4H7e+6GmtfWHRXUvk=,tag:Tr7UeIcmQqCpcF9eINW94g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
