apiVersion: v1
kind: Secret
metadata:
    name: glance-secrets
    namespace: glance
type: Opaque
stringData:
    weather-location: ENC[AES256_GCM,data:3Tg04sklQtHcVE7AtFo0Ny10kYrj6tOh2g==,iv:SHir5mlbW14oU0MvPBjHUQdSei+H4p3wyskKCxe31Co=,tag:YMYuE1Q0WYzPB0F7ItOHOA==,type:str]
    sonarr-api-key: ENC[AES256_GCM,data:pGFR768nGA5P6VboKWL2MAZaLbRAlSAi2RXmWwbqED8=,iv:FqLioy8Btt78JgiqAzg7lDTBDB57X6C61zqdunZLp8w=,tag:jtMR5PdYGrV+4pDgSt1ZXQ==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:azoKi/y4zp21ZxbpwxkmYlv3iz5Nrd3yGtUNeZAD3Q4=,iv:fbVfU1xhN1z+76+f9APOBJxeCLa3l0qsMv5YNiY64MA=,tag:RPSvRTre170JxKR6Cuu8Vw==,type:str]
    github-token: ENC[AES256_GCM,data:Zk8uE79KCAdx+xTeh+dW/1OyhahWePqUIg/TxqXXbENKMR5ylWTk3V4AIcwgbT46x2+EMVfsjLgsW9UL7zGmQxI1C24F6M2vQmewK4LAL7Th+KCSIjuBuC6D/0vY,iv:kIuHEtuoy4cnn9r+XDSNVSM9SLZpxjHF9zF83Ev9x9k=,tag:GlmX/SiRdF8kuauid1Gm5Q==,type:str]
    pihole-token: ENC[AES256_GCM,data:MLZRsz9Hjqu+sva/FWJP,iv:Ayv/9QFuK72KSSQgliAluhA5xz3QQZdIRFMgAqjLo5I=,tag:zUc5AM86c8xqWjMdEMAB3Q==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSTJXS1NlSlRhMy9VSDJw
            dmVMa2RWaHF5UFdjK1YvZVRacXpyNjBPMmxvCkF1ODdJcVF0Q1NraEd2V3Z6VUJx
            RW9ocDNvNng3Z21ycnYxcC95dldNUTQKLS0tIGNzMldnUWZkOTJ6WEpuRjJFR0ZT
            ZVNYZDNLRHVqWDBtS3BYdE5Uc0pPb2cKXB9wcajeXbVrb8hu0zvpvjGk0i0Ksy9T
            vURom/zc+VvhwDR8sBls3W3WBlw45XBM9iRRPjJEXkGNzyWlU4IRZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T00:36:27Z"
    mac: ENC[AES256_GCM,data:3APRmOb5s6QzsOUYO2ZirCtS9mSsHP7aUM1/LblqC4a3KBowTlYxXbimL4+tXcLRe/KR28/nj9AX3yeUGlWu4mVTwMqTWylkDYsUqP5SA/idNWEIEulm/b0Kva+b4b18uMHiIpU1/m24Q0UZ7fafTZFEdvABgxaban6h5f4pLSM=,iv:aNCcE96GdTLlZcCQnj37DyIdPQIxYDskIkUZ9sba6yA=,tag:C1PVIAfnD8gO6mhkUgGANg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
