apiVersion: v1
kind: Secret
metadata:
    name: glance-secrets
    namespace: glance
type: Opaque
stringData:
    weather-location: ENC[AES256_GCM,data:kw7PegoKK0RmBEQQxw0ixx7CVRiivmN08w==,iv:qpD7jm/2QUjOxbjBrUWVr362i1c8AQ2VEELNOen9MJ4=,tag:iItHkv766sg/59Ojv+nWJQ==,type:str]
    sonarr-api-key: ENC[AES256_GCM,data:GVtQf2AS2M9CEb1S9S1Z9qvQYYXb0LM0v0LbfKiGwj4=,iv:UGdKpViDf8RplUffWVUcfevB5/8O8MJuAnoft4uciQw=,tag:YU0P/mwZEhs/a8/HGYlRHQ==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:aSEYFh/lIn641YzGUVZhSlyCy6Ud0waoNRCaNHyE6Ww=,iv:9mmnZoUF8mV3FACvscMnrxFeF3pMZTVA7YcTtOxS3DE=,tag:prS4tlgkexul5yZ0sdJFew==,type:str]
    github-token: ENC[AES256_GCM,data:jEHbfHyj6HhCWDjq2JDEfz3NjocmxfGRR9V1vHq1epyZvUw+RtujJbvf6udc9ReUOfqdbVdfmBYq3bi1AtSF38CEI5Ajf2QE+4B9ztUypuQ8J0xi3ivlr0RO1SfN,iv:X34NRkOCeO0khLlBQg+eYCkRBto2gZueNunp7AneZkM=,tag:inyLgK3cHh/yeJW58AlLbw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSTJXS1NlSlRhMy9VSDJw
            dmVMa2RWaHF5UFdjK1YvZVRacXpyNjBPMmxvCkF1ODdJcVF0Q1NraEd2V3Z6VUJx
            RW9ocDNvNng3Z21ycnYxcC95dldNUTQKLS0tIGNzMldnUWZkOTJ6WEpuRjJFR0ZT
            ZVNYZDNLRHVqWDBtS3BYdE5Uc0pPb2cKXB9wcajeXbVrb8hu0zvpvjGk0i0Ksy9T
            vURom/zc+VvhwDR8sBls3W3WBlw45XBM9iRRPjJEXkGNzyWlU4IRZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:40:27Z"
    mac: ENC[AES256_GCM,data:LA71FQ7y21LBhkk0X1G5YCxEtnKhlcwtmTkoHywQfp4Ngl04aNtK390ydTIlBKXBdNfybMYAb0JUQE35iaGwtv//BclTQqeL6mSm4te8wM3Uo8fDmXwF7QJPnNVNmUweHKadryOn1Vu+pgYsMGy36b791ZDdmhmXz8Xh218gSj4=,iv:g5Zdf7kj0b1Cacti9ZbQoMpSVyZmHbrk0UoWjV8Ozec=,tag:LW9yeJLl/j5RBFju0PQfxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
