apiVersion: v1
kind: Secret
metadata:
    name: headscale-secrets
    namespace: headscale
type: Opaque
stringData:
    headplane-cookie-secret: ENC[AES256_GCM,data:YDYBiDWVX2Ca8Uc/xdTPqCEWwsK1+jAAYJEwd2+dMFVM1VU45S2JDbFCxS0=,iv:QTPq8G8zoiqq7Rzroi86dD5hmZQz/92acwJqd42L5Mw=,tag:SBiwr1IFOm0JmdfsMdjFtw==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:Q6FlMn9/Pk8cuEv/gnt/3k3foY2YjRcyckh75cE1fZrTsqFJK8OcDg==,iv:1j/E6TBZtIXgYyJCRGHBa7QoFZ/Grb+dQvz3NKIBIhc=,tag:D25GRuCZpy0793SmRIuNPA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:5uN4G92qM9NamFQOpn97ngMjV3UgYcSAuooi4d6pvng=,iv:jdITdZR/E/mKdm8ZiNHLq9vhyWOEC+PWsYx/1l17nAc=,tag:lZupBqzlwR1scrtIDt7EJQ==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:DkcbbaiW8ngXAN5GVMIDmhDWRxTztLBJzWvZlR0lhBZ+2iJG,iv:iOYXsz8TBgNemvrsuUJ9BBbZRvvNvbTzhfC9pXTSSlY=,tag:ZQ6ObXBZXOdUAPanOfXczw==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZm0zdW9SUU1kUWhyTzY0
            b01TOExIVUh0VXd5OTd6N0phSk04dUNEaXdjClZMUXVEaTlxUXh6QmRBNlhyeTV3
            V0dzQzFkcFAybUxiYklURTJEOU0zWTgKLS0tIEJoWFMwK3BuTXhjZTRqLytldFZR
            Ym9GL1JMTXVSTzJsbmV2ak1TWE5iZDQK3+yeYQxfpm6ejDSaf4kBvE7ZanKx/bS+
            IDImCbkEhx1Lfjt8llBWpMv93+Q50pDWuZ6y2Rh+DjB3Dj9g4VEoGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T01:35:49Z"
    mac: ENC[AES256_GCM,data:UhVA4wtDIMMPwVq2OCMfcrsHXMg2mNBOlW6GYqetIgJ3KbnDbpn5iTBDy7QB2sF2F7W1MhPzBTDVxvJmkKl9BWCan2+WAkGNol/TBYSPrSZ2wEqAsl/RxL1mw1MRe6/AbQr5NWAgiYY0H2F8AkZ58C2L+AxGM8p1R6TZqEoXlV0=,iv:nDLNDPSnnD2NcmNe8mXmLStwtd2uG2QF0rRYvSJ/AHs=,tag:E+tdg5RVnAJ3xgiF04CSlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
