apiVersion: v1
stringData:
    headplane-cookie-secret: ENC[AES256_GCM,data:YDYBiDWVX2Ca8Uc/xdTPqCEWwsK1+jAAYJEwd2+dMFVM1VU45S2JDbFCxS0=,iv:QTPq8G8zoiqq7Rzroi86dD5hmZQz/92acwJqd42L5Mw=,tag:SBiwr1IFOm0JmdfsMdjFtw==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:HuWKBigzqiVakus02p2+hxtAW/qAOHYsy2IawqMfHJgGCfTBzbFUsZ2La6DdUMzQ6INk/3aeVbs=,iv:QCWDvnQxKEuG+iY+vOchl5TmV/KyVXn1iEiBzXNVFb0=,tag:B99mZp6L6drjZvT6O3CKKw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:5uN4G92qM9NamFQOpn97ngMjV3UgYcSAuooi4d6pvng=,iv:jdITdZR/E/mKdm8ZiNHLq9vhyWOEC+PWsYx/1l17nAc=,tag:lZupBqzlwR1scrtIDt7EJQ==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:DkcbbaiW8ngXAN5GVMIDmhDWRxTztLBJzWvZlR0lhBZ+2iJG,iv:iOYXsz8TBgNemvrsuUJ9BBbZRvvNvbTzhfC9pXTSSlY=,tag:ZQ6ObXBZXOdUAPanOfXczw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: headscale-secrets
    namespace: headscale
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZm0zdW9SUU1kUWhyTzY0
            b01TOExIVUh0VXd5OTd6N0phSk04dUNEaXdjClZMUXVEaTlxUXh6QmRBNlhyeTV3
            V0dzQzFkcFAybUxiYklURTJEOU0zWTgKLS0tIEJoWFMwK3BuTXhjZTRqLytldFZR
            Ym9GL1JMTXVSTzJsbmV2ak1TWE5iZDQK3+yeYQxfpm6ejDSaf4kBvE7ZanKx/bS+
            IDImCbkEhx1Lfjt8llBWpMv93+Q50pDWuZ6y2Rh+DjB3Dj9g4VEoGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T00:30:36Z"
    mac: ENC[AES256_GCM,data:JTpllp7p8ZGPNz4gstuZDVXB4SyICBxu9gPty5iAvizADq9BZLzhpHWNg+mNBz3EwLvskLY6f7B0xCyRQVj0hhuMPfGW0uqkqk/e/gWnfS6O8c8qs09y2lDOdTGO1zM3A7u5fm/U6KpFgWugkHsI/ZqkF14U3iUn6HcF/0+Iwr4=,iv:gdGA9t9R/pqeFDQ3x7AX62cdRyq14IfbQitGk+rp0hM=,tag:+v/+v6oenh+4on76/9YJVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
