apiVersion: v1
data:
    client-secret: ENC[AES256_GCM,data:N5+Wtag2KqBYHCwhyVbuXVawVQLIkHhqlfSpgaEbgBXDLqOPyRS4cpkgyvQ=,iv:sb6CJJh6bULehPpyk0gfrzB0MNmO8yXIk/WiRKKzrCQ=,tag:2C+LXbthmKXrrsZVROcCxw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: headscale-oidc
    namespace: headscale
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRzZzbHUyYWFPVExuUUpQ
            VjViMlUzK3dhdlFFT2I0VFZkUjVoM0t1MlNzCmt5aStObWkyZXBhYjBSMy9MenRS
            V2g1SVlNeEpKN1BIMFppaDkwcE5kKzgKLS0tIHNmYTN5V3AveGc0RUpESjBhYng2
            YmpYanJPWW5nRlRFa285TXdKVSs5U3cKNbcOmWNTWCGTKizBdy6SAO8oeuWnGMjT
            F3wOrdpWAke13f65g7HIZH3F0dARJt3G9LrZDSYD4aq1wTm257tSKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:29:46Z"
    mac: ENC[AES256_GCM,data:C9hjAWC+7RhZniiqzMwr68WXrG08fnM67d1U6pbkQDHhp38K9ZpkkP9bg3dfer9IwLVY3ZANfLoudqqP7i1QBfyPsamAGwbtbdouOVb11ADdM+3facRsOqRbpvrgGfF8vnAhiYXe2HUpO/n6hksleEZtCgvXhvpC+lvDxW9FBpw=,iv:iML8zXvKS3jU3O+gDpexbhrlKw7eDkEfh3ii/XHD1sg=,tag:yOyEcGYzlZANNk9tFj4Gjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
