apiVersion: v1
kind: Secret
metadata:
    name: headscale-secrets
    namespace: headscale
type: Opaque
stringData:
    headplane-cookie-secret: ENC[AES256_GCM,data:zr6WQOaSfXhb31HD7arilK8etDKiZ2Gpbf85e+WXSYX+YnGcAecNqwcDaJc=,iv:pTOPa0sN82m9OttAsRumLibjCb3hfMhUe5cKu3BXiZw=,tag:0YjYiuhbZCPc8WGs9t2eSw==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:uc6JIOIF3TrdjuguQaxx6wxxWHx88xqBIH3DnhQbnh+MhRHTsdldRA==,iv:w0wPU6cBs5+3llBGYJ5pMznFuBeqYUd+9eSApLLOZFE=,tag:iluMemUA+ezcBllKZsix3g==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:f5yeYzQEr9+LHWOHl9qLwzzmtyLbRiwUObQ+VUhqK6g=,iv:d+fZd/YUu7IZ5bjx087jzfEa62qx3OmyYwN0l7qVg/w=,tag:IIQAI7NS7NhtRfIiqVlthQ==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:JAnReIZrjO8eAjHjBwgbwu4MiV0Ni19rJDuPIMPG7C68nMGM,iv:3IANCsF66WOmRHYCaA/P+gHdkP2Qwi565MY9Addi7iQ=,tag:0QrWbXxTWhH49PDerHONVg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZVFPUWNxZDhleXRVbUcr
            TW9ob3pHekZlRGR2LzgwcWFNanpFR09tbTJZCk5jOFZWWk1MWkNxS2tuaHNvWHlR
            MzdiZldIbnFKRFQwZzdmRWRuRVRWeWsKLS0tIDhMY2ZoTmxnYWhETUozbnJSWE5L
            OWoxcHVNQm8rMzJyaG9tSVZ2MlFJMDAKaCDrwVDG5NU2E6er28Cw1AywP8YDSOt+
            QiRlZEr295aqSAISK+6SlgX5bJa3Y+tdOPkUL3JtrJSMQQsvwm+stA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T01:41:18Z"
    mac: ENC[AES256_GCM,data:uf8xNeMi2aUJK5K+B5i6CcFKg+XbKAd7KvformH9ebU97DJi9Qjd7Lj/TLCanYK7nQfhKDOnEYcuXm/5S9RIon+zOyQ83M1qcIzsQ0X0mpHU4rim+I6an337FndNwgXf4PyF1+OXzMfTGUw8mrIoB23ExQ5aji72wxf/xhRmZqE=,iv:h49R+qyM+BUHb3ERLfp7MErx3hL2Obi6RNg25TrIw5c=,tag:HqRzYJXd8lZakzbx5dlqEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
