apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-router
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/tailscale-router
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: headscale
