apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: headscale
data:
  config.yaml: |
    server_url: https://headscale.coredev.uk
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
      allocation: sequential
    
    derp:
      server:
        enabled: false
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      auto_update_enabled: true
      update_frequency: 24h
    
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite
    
    oidc:
      only_start_if_oidc_is_available: true
      issuer: https://id.home.coredev.uk
      client_id: d5bb0835-b786-4356-b634-576b32a021ad
      client_secret_path: /etc/headscale/secrets/client-secret
      scope:
        - openid
        - email
        - profile
      allowed_domains:
        - coredev.uk
      strip_email_domain: true
    
    policy:
      mode: file
      path: /etc/headscale/acl.json
    
    log:
      level: info
      format: text
  
  acl.json: |
    {
      "tagOwners": {
        "tag:subnet-router": ["autogroup:admin"]
      },
      "autoApprovers": {
        "routes": {
          "10.43.0.0/16": ["tag:subnet-router"],
          "192.168.20.0/24": ["tag:subnet-router"]
        }
      },
      "acls": [
        {
          "action": "accept",
          "src": ["*"],
          "dst": ["*:*"]
        }
      ]
    }
