apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr-ingressroute
  namespace: huntarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`huntarr.home.coredev.uk`)
      kind: Rule
      services:
        - name: huntarr
          port: 9705
  tls:
    secretName: huntarr-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: huntarr-redirect
  namespace: huntarr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`huntarr.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: huntarr
          port: 9705
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: huntarr
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: huntarr-tls
  namespace: huntarr
spec:
  secretName: huntarr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - huntarr.home.coredev.uk
