apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: pocket-id
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:gdGKVcZYTS2D7pvcAbZab7ly1PRfOwfie/Mz8GEucJWRNioU2FgCllnP/is=,iv:5p3QkDacjSaK5ErcuiuTvWxBq6M/uDtnM8GSchuYkes=,tag:i/ykutaC62sWYdQDPsdKrw==,type:str]
    key-seed: ENC[AES256_GCM,data:7MfVyzo8Zi2gXelSueDhX0cwRrQx8WyD8KtLkNm65kra9NoSVYDjKUvsDD4=,iv:x42QddICW+HO9ghCiioetn8iwYuqKDTdsq2jfj+syzA=,tag:BNogYeWUDidxqOwzVYzApQ==,type:str]
    admin-password: ENC[AES256_GCM,data:X/YzTnXoNNubNr71wYsz,iv:43IXM+rrbl/D14GFeFKnwn1kGuErajnoKmexLKb0VgA=,tag:XLda2JYFVovCepfJMr3GNA==,type:str]
    base-dn: ENC[AES256_GCM,data:RV0RBaSeLIWcciJDRmg5+R1Z,iv:4Dy2eM1C10TY9gbEhaQjDkOFP+DZrfp5fM2txoB1FLI=,tag:LgqM+S9o/dRRl5pt/uvb8w==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZUZSeHpuZ0lOb1NHblhT
            WnZpcDNyK1ZIc3JPR1ZjVDlONWNSSlA0bkJvCnZhb0FocWlQYWZuZFNkL0VXNzk5
            VHE2SEhnbER5b1hPUnlGdGtlaFBSQUkKLS0tIEhwL2J1UjNZQ1FmZ2ZZVVRzc284
            T2tJZEFZOTRDT05Fd1htYVhrOWhwTFEKQRiVGBvIPg3QIZLlB9/sNGNtiWj/p9xl
            PWiQUDK5s3M+HQ5SlChG1PcBGXzfF+Puh/Nl82J3aqtP59/PdzUP3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T13:16:56Z"
    mac: ENC[AES256_GCM,data:tY5WmyxqJmnLpCqE07D7KYDiPA2UFQu5o1Y93kA3H/QVx5p8mV+LhuwPnpCLzPmrSLkqijBIxmqTr/qKiwBfBPLgP5yJWoxaaJth6sbOnj+9I5ES9W42ZNUkWOb2AvaYYGfLWyiNI2XqpFDz4+cCBaizc5UBY7N+lS6uRq1uNSM=,iv:b3I0aObUL2FCjbcEGF3WyHuENOy3MOeRU0bIQXu6jdc=,tag:dHLEuoic9sBRZU8iSpGA2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
