apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: pocket-id
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:sjbQtk+Q6CCW2k0W1dURcbPdHG4FBHhbiaXbkKjkT/3qZd6Zo2K42OvtTnU=,iv:Vc+tf+oc3O5dHcRhRX63TsxcR7JrNEm9IJOSjD+hUzE=,tag:7Wu7RygY+WsDNp8tpbpKsQ==,type:str]
    key-seed: ENC[AES256_GCM,data:No1Db0WvFqzPVzaBEvA8th2621qHQ8m7AMjYzRAPlSMsfHFf+3f+HDbk2Z0=,iv:gBRC15jRI+Gi+NurYPhSe9bLKUxGJjlQ4/rJoFjIh/M=,tag:CGq1y7W0U0+aLEhnTRcCFg==,type:str]
    admin-password: ENC[AES256_GCM,data:LrSD8X26FPZkiK1uJCdb2qPXkKhGJkXleIVTWuZ/T8w=,iv:L2/fQmD9ScWEthUkMXK16TnVB9lFMpXVA6eRQRTrJ8M=,tag:2AwknMX9ZfbLxRpBzKCxJQ==,type:str]
    base-dn: ENC[AES256_GCM,data:2Hn1ixTjkVaESx1IowoI9DpZ,iv:bPQcnvYzpzJlPIBzv0pfhiQQMOXDAh+JzOpXd3Bjfss=,tag:rzP0LIQSEj971bJ7JDkHIA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUzNzMkxNenNyc3p0RWdT
            OE9wSFcrRzBKOEJSYmp0Qk9meTR0UFlzTVVFCnBKYVpjQSs0UjlsUzJIdEEwdENh
            eisrM0hpNE80WlZLNzVxM3pLNDZPcTAKLS0tIFRCTld3RXdYUTlwZTh3SExud3NH
            aEk4c2JOK3UveEFyRVU4dVpXa0F3Z1EKD0h+LDzuPH7g67z+LgoP3YypQjdQX1d+
            sz9JSSoCISnIATzvEnO72VTm3kMgfwgtG2mTm3PLgYSXNpGaQfOR8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T12:26:35Z"
    mac: ENC[AES256_GCM,data:i9ounjJRY7WOzDqJgXhTlqpZI8f5ZIJy05elq4gh+G1UfbstWhrRERlVxifrAPMTZ+WZLgblB65+jnIlB6MOBAw8y0seEboTrxEmY1JJ+8pQ3hVRMx1EiFyshirF3+7Zz7UsUbIgclwzGyfo3+7iBzzo7HcINVVO1y0TVwF6KHg=,iv:myBPEmIYis7aODeq31ZS0dh0ikmRGRfCjMaKC1CscfU=,tag:ZE8kMLRYZrCqP4Z3rwoiPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
