apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: pocket-id
type: Opaque
stringData:
    lldap-admin-password: ENC[AES256_GCM,data:rxXRrAiEUDoBqdyNnb0=,iv:NXLPg19Qiy7RHRlQtNNCfxxg98O5ctlVIPvp6qx28iA=,tag:hysChLj8vDFcI7Hpxf2deQ==,type:str]
    lldap-jwt-secret: ENC[AES256_GCM,data:VpaMRCVR4d0A8gdPn/AW9BgC3JVzulW+dV8zjdV/UNRDNnHgKRhi+YmgADI=,iv:B66XK/M3hotH4RHARUiuBInp9sok8pQI3isAGf1Q+Ko=,tag:Cd6sDYtc9eI5gii5TPgf/Q==,type:str]
    lldap-key-seed: ENC[AES256_GCM,data:CW730IzS5W70oVpGuY75OuGNUM5P5AC+65H8ot6HncAGhQq8PHmxGxFt5/w=,iv:eHwaVv4lRf3GlTuV713TUl7gKpHv+e0zM+q0s0CJIjs=,tag:Of9gt7LDoawQ717rb+1Tsg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZUZSeHpuZ0lOb1NHblhT
            WnZpcDNyK1ZIc3JPR1ZjVDlONWNSSlA0bkJvCnZhb0FocWlQYWZuZFNkL0VXNzk5
            VHE2SEhnbER5b1hPUnlGdGtlaFBSQUkKLS0tIEhwL2J1UjNZQ1FmZ2ZZVVRzc284
            T2tJZEFZOTRDT05Fd1htYVhrOWhwTFEKQRiVGBvIPg3QIZLlB9/sNGNtiWj/p9xl
            PWiQUDK5s3M+HQ5SlChG1PcBGXzfF+Puh/Nl82J3aqtP59/PdzUP3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T13:03:24Z"
    mac: ENC[AES256_GCM,data:sZSxwpCZeiW4KftFGB0g+TACFiwhRsWRyGC9DjnwI/BAYBUYYxH+YQhBHq3wyyxtNMnatJBuyxZO4ioSP4Z2OqNM8btRvFDkFjGTsdON4T4MPPsYHm+/837xoe6hPQXoDvC4PKmR5kjURw/SBX/Us5AnfRlJS01saEFIYjTOVaU=,iv:aoKmIykdABnHTk79tqOBDjcvxc3Z7XYG+lZ7RaOqdW0=,tag:LWDd5o9zFkbUFHH8fMQt/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
