# IMPORTANT: This file must be encrypted with SOPS before committing!
# Run: sops --encrypt --in-place k8s/pocket-id/secrets/tinyauth-secrets.yaml
#
# After deploying PocketID, create an OIDC client with:
#   - Redirect URI: https://tinyauth.home.coredev.uk/api/oauth/callback/pocketid
#   - Scopes: openid, profile, email, groups
# Then update these values with the generated client_id and client_secret
apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-secrets
    namespace: pocket-id
type: Opaque
stringData:
    #ENC[AES256_GCM,data:sVn66LpeVxY9CNRl0m1EIfKaYPBdHAUE37C5OtLyPKf7ikX7zNFr,iv:IuSRYcufSEhWp30SxDXk+RfEF4OaqMVnqjr43JAknA0=,tag:IGcQhmI51B7aO9mP6e8NaA==,type:comment]
    secret-key: ENC[AES256_GCM,data:viUezAAViex0SEzhsz+wwEXQHFrSJxp3mTsBoXB5vYBUX3tmNskv31mOlXI=,iv:5J8Z7LeLdjvs5KsS4D21nCj1PHWf4D64ckPllPiU+FI=,tag:2O7R9X4aaTXX2AscnkLbQw==,type:str]
    #ENC[AES256_GCM,data:KYR481h9ugDIe1DlZpdr1RE6uu5Nod+jw5M=,iv:BFYNrZMvDMK3xQp0ixGb0kWOMPNukDwAWW5kLOpT39w=,tag:VyqpxufgA8KT+ccSlyUZEA==,type:comment]
    client-id: ENC[AES256_GCM,data:ehlPwY7WePcYddpBs4HIjZBD+bvIyaAkz8FZQ8+kHq4=,iv:YsWA6g8htF4J+BzUn3yrNvuPIffN+eBCxlh7164R7Bo=,tag:96AVXQ2J760VtsRL9CWv4Q==,type:str]
    client-secret: ENC[AES256_GCM,data:Bby8AcfCaU5KIpjRxFI3ZqX78+xdrxaUVbwdPLmdkxlWXmFV,iv:BlAbzZTfhZE0gOOsVgzKq0GgAkQimExdJrlSPs3LW+k=,tag:5tg3hkfVzDf8WRlyOHvfkg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1E5cFA4MG9PczVyb1Zo
            bHRML3lDRWpjOXlDTDdCK1ZBMGI4Q01IRVRRCjNWbHVueWkrZjdXWGxVNEIyRGI2
            a1p0K0JiVit6TmlqNDg5V0hTaFFVbkEKLS0tIEZTbk5MWDd3UURHWktxa3djSEdl
            REl2ckI1NStnRk8xZVZmc2hVV1FjMHMK4RNuApg5kwWpiCB2uQqenTeIyDp/loYm
            DqiVhtTv9veGg5TctrQgc38B7IPZkWyJ3YXjojvvMrQvYbdPlEJOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:34:30Z"
    mac: ENC[AES256_GCM,data:qMK5WZhQm37gPbBOdw12uRwoy/lOt2eFUs4PzdQCpdie94OhnoV9ohM0jg8l+Tqbvlr+s/wzil0v/lGl/zmnOFpipB7n5UYQGmpiDvstCi4Pe2NP7lpq/wX0w8xmFi6fzRvl8FJ35gyiB+KxeSfhMw9aIX4EQS22mOaDwQTg8eA=,iv:/WoO8LXhGd2083NmTyEdczs4kkMjjI/vqALQwiBITVU=,tag:AhrvcUYAEzOs81c3pi78yQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
