apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-secrets
    namespace: pocket-id
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:viUezAAViex0SEzhsz+wwEXQHFrSJxp3mTsBoXB5vYBUX3tmNskv31mOlXI=,iv:5J8Z7LeLdjvs5KsS4D21nCj1PHWf4D64ckPllPiU+FI=,tag:2O7R9X4aaTXX2AscnkLbQw==,type:str]
    client-id: ENC[AES256_GCM,data:jtkoCGOldp7Z7JBcEOL9xcZgcBElpoGDVAhZWpMvZ3o8Xw9i,iv:Eif2wUqtnDt9/aLRLjiueXFb+B6jxoLWruReweFmA10=,tag:QovjbWy1xV/kluUc/5PVRQ==,type:str]
    client-secret: ENC[AES256_GCM,data:DpKcoSq28t35maJqy11RIlVVjQJ1rqic+/zPZ2sh2BY=,iv:kIxHPsZHVzWGXs4QUCnOrEekxlLN/3mAdB4tgtXjcTE=,tag:XFxJ0VYTUg7xxH7TugHjJQ==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1E5cFA4MG9PczVyb1Zo
            bHRML3lDRWpjOXlDTDdCK1ZBMGI4Q01IRVRRCjNWbHVueWkrZjdXWGxVNEIyRGI2
            a1p0K0JiVit6TmlqNDg5V0hTaFFVbkEKLS0tIEZTbk5MWDd3UURHWktxa3djSEdl
            REl2ckI1NStnRk8xZVZmc2hVV1FjMHMK4RNuApg5kwWpiCB2uQqenTeIyDp/loYm
            DqiVhtTv9veGg5TctrQgc38B7IPZkWyJ3YXjojvvMrQvYbdPlEJOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T02:29:50Z"
    mac: ENC[AES256_GCM,data:bkOm+2C5nAeHZFc9J1D2gYTOf0kZdwPYLNXI2LglzV/KbmrhyugU0UvzbmVfoTt+tEqWO48DyoXi78fdwQiGQvY3tySKRprwld9BZLU4RsZ69MqYZkx7K+L9xtCaktiNiRXWIamdbaOo9XxwmTX+vO24bIVKOWGebW+mgmTIsk8=,iv:0g8dbAiVHS48X9Rqjh2X68V7ktNaU8KIQq/OEoZHKjc=,tag:Kn1TLTv4UPXmZ/T2eLSdhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
