apiVersion: v1
kind: Secret
metadata:
    name: tinyauth-secrets
    namespace: pocket-id
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:viUezAAViex0SEzhsz+wwEXQHFrSJxp3mTsBoXB5vYBUX3tmNskv31mOlXI=,iv:5J8Z7LeLdjvs5KsS4D21nCj1PHWf4D64ckPllPiU+FI=,tag:2O7R9X4aaTXX2AscnkLbQw==,type:str]
    client-id: ENC[AES256_GCM,data:ehlPwY7WePcYddpBs4HIjZBD+bvIyaAkz8FZQ8+kHq4=,iv:YsWA6g8htF4J+BzUn3yrNvuPIffN+eBCxlh7164R7Bo=,tag:96AVXQ2J760VtsRL9CWv4Q==,type:str]
    client-secret: ENC[AES256_GCM,data:Bby8AcfCaU5KIpjRxFI3ZqX78+xdrxaUVbwdPLmdkxlWXmFV,iv:BlAbzZTfhZE0gOOsVgzKq0GgAkQimExdJrlSPs3LW+k=,tag:5tg3hkfVzDf8WRlyOHvfkg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT1E5cFA4MG9PczVyb1Zo
            bHRML3lDRWpjOXlDTDdCK1ZBMGI4Q01IRVRRCjNWbHVueWkrZjdXWGxVNEIyRGI2
            a1p0K0JiVit6TmlqNDg5V0hTaFFVbkEKLS0tIEZTbk5MWDd3UURHWktxa3djSEdl
            REl2ckI1NStnRk8xZVZmc2hVV1FjMHMK4RNuApg5kwWpiCB2uQqenTeIyDp/loYm
            DqiVhtTv9veGg5TctrQgc38B7IPZkWyJ3YXjojvvMrQvYbdPlEJOEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:51:38Z"
    mac: ENC[AES256_GCM,data:ro5i1DmqedePHUnfczWLwewkQqjRdvd1S1fNlaYulr7s8CD2J5BTWUDf5rNZ0m9tIyVb19CM+f++HB6soQbCv3EyqyZyVLNDQi6pIy32V22NOrVUFDAfJNQ6Qra0LoJdlHt8zImifRArTCRcLKrTNNkZXq3Uhl5Tuu2+/XFTfCA=,iv:Z8RQ0YHWdd6puhC7SUWjYSCZ6k3daT4fTqCrFgpl8Yw=,tag:cY38Y1sNGJ8s2gn1L+v4Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
