apiVersion: v1
data:
    privatekey: ENC[AES256_GCM,data:wrnLL1AyFy2QTerhaunIgobHVPj2AIUxb398IhfaadeF5ubGBUAqn7ac+oLcz86VE0bnEb07rGWF3CIj,iv:yM/1au0HItXIBVbO6oaRQlarwqQ7W6N30FmTmuthVLU=,tag:47HuZLjnp/CFVatxnHZJsw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: wireguard-keys
    namespace: wireguard-client
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdmlCNjQvQ0hJUWJOR3BK
            clVpaHBkWG1tby9pYmJGNEJrMXZrTzEzZHdRCmUrQ0ZUMndTSXg0RnN3RllEYmhE
            SnIxNldYKzJVOFZyRC9LWFBaRVUwdzAKLS0tIFJ5T2lGd0R5TXVRU2lkMXpNQmpq
            c0NmaEM5bE80bVpGcmg1SVd6TFJySTgKalxoTnu7wluCFYGHTV2LuoZ38PIEj5fy
            iWH3OlwrkPjfvdwytaMXIc1cRBvS24YVy6RgLYGlSMWNmfAdV/c19Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T18:53:46Z"
    mac: ENC[AES256_GCM,data:zKjoJGwKv5X0fXuAW9HJG6BWQK6qQ9bRpoFqil3L/2mnCLUX+6N4nH3zuWQpeBd+5bbLJC2xfspLnEpcAaoTVT4LKFGIZMrQNelgv3yqrQMlGnPUGmBNlQZIoh6H+Cc0aT9lkMiti09yejYAi4A5SxbHlyB5esY6l5QoCvJggMg=,iv:aGparbJmJqwLTz9cFO8tY2VFYk2TMA8hFNaptp0Jjk4=,tag:k0r43D3kibb6RGzV6n2RnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
