apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authelia
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/authelia
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: longhorn
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: authelia-authelia
      namespace: authelia
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: authelia
      namespace: flux-system
