apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets/
  - cert-manager/
  - cert-issuers/
  - storage/
  - pihole/
  - intel-gpu/
  - metallb/
  - traefik/
  - cloudflare-tunnel/
