apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 2m
  path: ./k8s/jellyfin
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: shared-storage
    - name: intel-gpu
  wait: true
  timeout: 5m
