apiVersion: v1
data:
    cookie-secret: ENC[AES256_GCM,data:qvZQ7sA36IDk18Uz1lvEGubIMl/tK0+gVqx1CVJbXC9/ZQlPnp4sv8ye1NM=,iv:4QrheizSduuo1RLL/JnMmcAjtwNNtKjEjEN/gpt3KP8=,tag:Nxc8iHLrJ8Riwz20xx9Hkg==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:+0F1ebiuXSu2xHtbRz0rmI+r8CMraDTkPFVKd61Jg5TMFgT9y5UCNS0MQ+73VDe34m3Dzwk61QQ=,iv:nbEDJ/wf1AUT/qG3grLJb4w0REpLUBXZ6H3nyC71H7k=,tag:YXsYD/65UeMOMa+VZpq9Iw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:4u74PVSIDekrrjfwWYFhCCLqyM4/WvG12M6IHrgfdEM=,iv:p+6qk7+68MhYIbbFQvXNJcfhztFHDuzFXQNNbMB4TgM=,tag:trjfMSIHUzjuqPDrv040jw==,type:str]
    oidc-client-id: ENC[AES256_GCM,data:rCfZxtsgaJ3AfFggooVU/fIBoxENXH2uT9ZUbVH6EV2MD5r1,iv:LaLNL0QVgPGx0j/e1v1cgCJ0mRULmquGHD6Uh/O/VkY=,tag:jEN7O8tlMnzr2qxEH0e7mA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: headplane-secrets
    namespace: headplane
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZm0zdW9SUU1kUWhyTzY0
            b01TOExIVUh0VXd5OTd6N0phSk04dUNEaXdjClZMUXVEaTlxUXh6QmRBNlhyeTV3
            V0dzQzFkcFAybUxiYklURTJEOU0zWTgKLS0tIEJoWFMwK3BuTXhjZTRqLytldFZR
            Ym9GL1JMTXVSTzJsbmV2ak1TWE5iZDQK3+yeYQxfpm6ejDSaf4kBvE7ZanKx/bS+
            IDImCbkEhx1Lfjt8llBWpMv93+Q50pDWuZ6y2Rh+DjB3Dj9g4VEoGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T23:58:28Z"
    mac: ENC[AES256_GCM,data:ndr82t0zGftmapy4U/UUQzzWW18qYW7xMf/jR2M5bsbfyjaubx4jvJOPMU7mqGOyqL+ZTUhwrZEAgKLA+TyVEvspmLNNO5vAS988pBs0eyLRQ7azUilcJU+294WDULfe49aiAuXtkbMHHae6iB3kE6xoUkfM1m/FURibbAzlK+M=,iv:XpbBuabziT1rdpyi8y7+swemLVwL0/TAx7Kf7IOLMRE=,tag:74dt/HfxAWrsgItinfeeYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
