apiVersion: v1
data:
    cookie-secret: ENC[AES256_GCM,data:qvZQ7sA36IDk18Uz1lvEGubIMl/tK0+gVqx1CVJbXC9/ZQlPnp4sv8ye1NM=,iv:4QrheizSduuo1RLL/JnMmcAjtwNNtKjEjEN/gpt3KP8=,tag:Nxc8iHLrJ8Riwz20xx9Hkg==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:+0F1ebiuXSu2xHtbRz0rmI+r8CMraDTkPFVKd61Jg5TMFgT9y5UCNS0MQ+73VDe34m3Dzwk61QQ=,iv:nbEDJ/wf1AUT/qG3grLJb4w0REpLUBXZ6H3nyC71H7k=,tag:YXsYD/65UeMOMa+VZpq9Iw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:nf8wdm3TEN0sV/tM9BxtKjgm/c2ELGKbCZBTE5lLA07DPTVmkj/gcgBpra0=,iv:XvFzG5cRCxy4RsmvdNQADN6FLC9ZZtrL1m32WQHH5OI=,tag:Xq3M2hTVvTpA1VeQvWmbPA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: headplane-secrets
    namespace: headplane
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZm0zdW9SUU1kUWhyTzY0
            b01TOExIVUh0VXd5OTd6N0phSk04dUNEaXdjClZMUXVEaTlxUXh6QmRBNlhyeTV3
            V0dzQzFkcFAybUxiYklURTJEOU0zWTgKLS0tIEJoWFMwK3BuTXhjZTRqLytldFZR
            Ym9GL1JMTXVSTzJsbmV2ak1TWE5iZDQK3+yeYQxfpm6ejDSaf4kBvE7ZanKx/bS+
            IDImCbkEhx1Lfjt8llBWpMv93+Q50pDWuZ6y2Rh+DjB3Dj9g4VEoGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:51:24Z"
    mac: ENC[AES256_GCM,data:F8iNJAEyzi9aTGLry9v0FXbyXRpQni4pzWArlz+V7Rx4jFJRXH4183a0tIFXlQ/zN7X3mojnKNXg+aAB0UD7Px1uRfMlzUGqRINZXC66RCEH6VcCrH+uFMcWipEmRvZiQuEPqkkYPol420dLpuyHHyLCK9SbpSbHwwX+p+xm3Y0=,iv:hx1h24GOE2Bbd+4RKgSRzg+22FWrDcF/gaKKtqCI/Mk=,tag:CoM081q0CQqCN+qyW3cdyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
