apiVersion: v1
data:
    cookie-secret: ENC[AES256_GCM,data:eYDuvLc+ouFdwK9Jxwt7eH3C8023anhM5hy/Xr7u5473LWwWb0cL649AqRxDlJY8HOwqo2flzY59yEO0,iv:Jw6n+wYzKqDmdceHE61ISJmEqq21gGsVjIFt1IQJlRY=,tag:aNO1vgn2L4jI5dbgIZcRxA==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:X+9IxQaHwfyVyK/Ox0u8grkPK4yFKTQjKRsRCvURo41GJ6Fn,iv:kZ1GC/QFf2uu2wKMDt+xkB8Jo482Je4Rorf5efaWqxo=,tag:D5r3Hs1Dy3TFecUxKLhZww==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:dasEbak0iZyFcDGd53bq6WNGr2AD2eDSUh/AxDneQRyWgy3VlwKkNnY+shk=,iv:iniN2NnkJ2ljtyZ6aRoDsUxbwo7hePJgE4ohP4psWm8=,tag:cU44xSVyyUjZpD/M9egkyA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: headplane-secrets
    namespace: headplane
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVmI1RUdtMmlrWmhOVnZw
            eFNscTZSTUY4NlkyV2ZnYlpjWFB1dWZ6U0dNCjdhMWdjWVZUbS8vWlFCZWFENFNw
            TVZ2QU1CWENXYWtvRGg3Y0t2SEVHdzAKLS0tIENTM0xMTVFLemtEdEk5TVo2SElJ
            V3NXWXFyZXNUOEpFZ3BuUzNOZDNWVUUKGrhtfUiuVerYOUhYuJsgoRBn+PIb4zKI
            fM6jih05eM5VBF9CEHTsY1Kr5snn2WXieQ7L0w5CLF9N+cO9V2QyGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:31:17Z"
    mac: ENC[AES256_GCM,data:hBiZO3X25KRGRV3YugOwJ+FdyzFEboulYHqPWavDaZHFbSeRtSuRsz69mdAToo6KyDuFD7A3LICOyND3qRYutVG6UaTzGgCezqRG89FteqkUDZa5ZY4i8mIgmfEA12FkslgWF7P7KIh1iDgKvY6s2wwVv16Ml9PWanLYcIzA1yg=,iv:wpXtS9k9gAKPXBuqK9OCO5WZYB/xPWKq8LSg64r7P68=,tag:+bw2tg0kpM20DNbMlBWnXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
