apiVersion: v1
data:
    cookie-secret: ENC[AES256_GCM,data:SG/4HeRlwsgHq/xrIArQz5obhFHNZej/UiCkATjHiX/RmqUDzu8cgHf1jxkgrs5cyQu3QuUXAbAeVrzz,iv:zr3IWwmyJNWhdoq8KagI/KMhL6ZaSKg0iFp4/b7XdJo=,tag:xfK2xrKT9hk+ptiAK0YiFQ==,type:str]
    headscale-api-key: ENC[AES256_GCM,data:dPa2hR98VTiyotTXt+XzevTXIuRoM5siSuUIydG8atfsDCK58e+GmSIAgrnf82i5EIWQaVoGBlk=,iv:PcO1tcKnNY2Z99tiQLoobjswqYzaoeHSWngDk6KvdQ8=,tag:9PAyvkRaaZfOHIkntqrBHw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:FsZB3vXU7KNJ5W1Cxk7vrcGpO0GBB8CQqLeQCcwdd1IlEHU16r0/G8hgLL8=,iv:vgsY14aQq+3UcIKr2SYbE+6/msmJloxT9Hy9mSCVxQY=,tag:abGtH9ddKcr7Ie0uNnzj/A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: headplane-secrets
    namespace: headplane
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR1JMbzZlQVdlWm5WRVZS
            VUVIWTZTUkhHdktCT29obGJMVVl2Znd5M0c4ClFHaVBNQm1EYmQrVVRiOWluK2hJ
            ZURoVk1Pa08wU0QrOU5UOEQxS2RlSk0KLS0tIFNSdmhxRklXTkxIYnZxYWlnYUho
            bGhaQlhTK09Ia2lCWkt6SWh1N0tWVkkKSIjUHfcKCO6/elzuu43c9tJkuXFF+GjB
            yHZvAmNNIHG59GrOWE51TYLD8UbQZsxHJKE3rd0S9jmXdWJJLPLdOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:42:58Z"
    mac: ENC[AES256_GCM,data:L75p5mxGOYXBTAxr28I6W1KjkDPt2Ho4cbwV6C2RHYFSCwPh/dOBh5xCaBr9lYac0zr742vT11n/FaQGptnYEZTtmCDDM4ehgl2qc6pf77zYrKzW/AUOJSSvPMWoQhbbHM1MOSdbYsrSOAhJgXdAvKeMd15cwsX1/5n3x5hhB4w=,iv:iFwB3iiBVVsJPdajocj4xzko7GFgAt4wNCxlGNN0piE=,tag:qqNrzbs7sC7pAKs0CnVGXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
