apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authelia

resources:
  - lldap.yaml
  - lldap-ingress.yaml
  - redis.yaml
  - deployment.yaml
  - ingress.yaml
  - middleware.yaml

configMapGenerator:
  - name: authelia-config
    files:
      - configuration.yml
