apiVersion: v1
kind: Secret
metadata:
    name: mediamanager-secrets
    namespace: mediamanager
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:grP2N0Lt/Eeh/yyE,iv:TCMBZrA/Heu910St6A4peyTd9NgER28kQus0kgXczaA=,tag:PtqSjhdl3sue1sPRdRkHBw==,type:str]
    client-id: ENC[AES256_GCM,data:n6cYvOEHgnhFnPdnLgqyZb40eQmZOCLqRyWyWQM1R0chpAKD,iv:v219VF3I7AKXmTMPcF0P1rCsJOPD4mG3DZsmGkAX3ZE=,tag:cwsRluzc4m4vD+8KxzfMuA==,type:str]
    client-secret: ENC[AES256_GCM,data:cBlY3kvx85XWFCazJLPWCZrC5HFDxUaev2jbe9tTjXY=,iv:wfMJXdtd5otqTY+ptAoF4uwLNJrkHxAldEZPvo34ReE=,tag:G8PPAsfft6dWYbOyWFgAcQ==,type:str]
    admin-emails: ENC[AES256_GCM,data:ZysmyK8o01Wf64eBoZ8DUxT5AJ703iOy,iv:PixEjj2iHUdvWW+xT/JqjXkEgJQBfZH6hw7lU/3bYNY=,tag:dqlruLQWiDxTHWwFNbnItQ==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbXBPRHFBMXJobkQ3anc5
            UXFLSTA0WmRBZmJhTEo2RDF4UUt0M0ViV25vCnVwMHlGdXN4YlNNY0hxQjJ1RDNS
            M2daRlo3ZjlEMWtJcGJtQUlqNC9PRDgKLS0tIFpaVFc2ODZENmZ5aGhLeXcrR1hl
            d0lXV1RJUFJhVnlPMXdteEljdjFyd1EK7t7KMwLhvfYfF/wXiKln2yOrCRqoANym
            /4VF5H+XxP3qqtzznMUhSRVWvbB57SAV3unGfA3kiMwMGD8415wAHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T23:17:29Z"
    mac: ENC[AES256_GCM,data:bAYOn6GqnV8IH9jUqUBPEr7BWRXUNoZcBV7S587CHi9GJCGTWINveYncRL0FrfGU3UhEIZLzSaT3QEqdBLw8eRVmhNVSJUr955e4o5JiQAGkO3ABv7jQsQuSyXvKazQ4888GfWw5Ge+YhtdnCVYtoKz3snp/8dUTDkRpzpn8krA=,iv:0q86Bq0/9+CYDzIec3ziO/Z704RcCnqmDkTmrtkcItQ=,tag:A/+C/VaMTW/SbudweBFbDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
