apiVersion: v1
kind: Secret
metadata:
    name: mediamanager-secrets
    namespace: mediamanager
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:X09k7X6rEqEx7auC364P2l3UcUytHwpZU7M83aGf0mw=,iv:E01ayg+y+tnV0+uhUXBuGoYyCn54ZQDIz5jpZs32NA0=,tag:FOCuQdMmr8sHkwpyJjnvOQ==,type:str]
    token-secret: ENC[AES256_GCM,data:CFIJyyoKQHqdVAmInzAbRBHXb+MtaDGO/klCUzvsduXtTeY/WhXGpDNS32Nf6UkCse2MJeRGZZmwjNxf6RbjKg==,iv:I/j+GnfFDG++ATF6OHm3ixI/CN2l9+yTgLfpITsxOik=,tag:QzS+YUfkpST6PZpfW0G+Pw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:cw/6/UdeQ750bpA6GBu5yzgEL84qx8NM3FvKYgKU51dWFoS6HvLtiupi+QvmesgxmZJZ/JM7PIR/E/aatzlTpA==,iv:C6H77heGOLe4oQGtixxI/cUxxprrrMvjQ5lEG5lbIk4=,tag:ClEIgYHVV0U9XPBMuQJ8LA==,type:str]
    prowlarr-api-key: ENC[AES256_GCM,data:pORbqOXn0pAD3JmxLjRVnQQzuKTBVUyNonM7brS1HF8=,iv:di2teBcDQHgZW8Q+w6yq2yH2/bWmliAiqDw0A7HhdYo=,tag:8DEzLE7WCrUl6u7LnQVmZA==,type:str]
    qbittorrent-password: ENC[AES256_GCM,data:HoNw3rjaLnT+zCeZCoNg,iv:bfVEoPDPULwbm2OHY/IeNVwFincIKR49CaXE/tiUna0=,tag:VrN+KhTlu8aHlqJdmHb6VQ==,type:str]
    sabnzbd-api-key: ENC[AES256_GCM,data:yxiAwj6EpfbP1ccGS0QAHDjKFtkt3vpugDTk9qIrX6k=,iv:DjtmzOFhOpJ1DtSQTNwo2nnl9F2zvVNpfGtkX//HPhE=,tag:XDdsAln7MtXISNdBatEkOQ==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTlhiOSsySUIwZ3oyVVI4
            alhaSWMvaUpzUUw5UTV4THNCUlppNmVwejBZCjRVZTJMWmpzZUVJT21kaXNuU0tJ
            WUM4QnRNWkJFTjdKRHRjOEg0RmZ6Tk0KLS0tIHBycThwZlVNMjZDSldHZm9VTjV1
            MHowQ01wdXovSFR0V2dKMVBuWVh5WFkKZ5o6xqH51lBK/fJPPhclf1vCwG1UaTMz
            iO59vDD0nVE2QLclAZhUhhVtiZ2n1Gua/Ud9E4nAgcUF+jojjwr3NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T16:26:59Z"
    mac: ENC[AES256_GCM,data:TQSX6uZkANBs+tsiIKA6fr4NMgzPlV5w63g+63VAQz4NM5fW7x0aFY0IlWKCNBzpkvrfYF+pcpRuaYU9433xn8ANzlJYvNZA9nlHpwiQGWzen1qzlR/BkKQGCnjQo08iJfxM1AWkApCZITbU/H33Dfl10M0833hdoYdh/LTAB0A=,iv:FNeKhHCCD3nlLGob/yZbjSsmGHWq5ozuBLmibn8tsrc=,tag:zcM4t6K1vA98KODJkWmKBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
