apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/prowlarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: longhorn
    - name: pocket-id
    - name: sabnzbd
  wait: true
  timeout: 5m
