apiVersion: v1
kind: Namespace
metadata:
  name: prowlarr
  labels:
    name: prowlarr
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
