apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cleanuparr-ingressroute
  namespace: cleanuparr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cleanuparr.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: authelia-forwardauth
          namespace: authelia
      services:
        - name: cleanuparr
          port: 11011
  tls:
    secretName: cleanuparr-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cleanuparr-redirect
  namespace: cleanuparr
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`cleanuparr.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
      services:
        - name: cleanuparr
          port: 11011
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: cleanuparr
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cleanuparr-tls
  namespace: cleanuparr
spec:
  secretName: cleanuparr-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - cleanuparr.home.coredev.uk
