apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cleanuparr

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - storage.yaml

configMapGenerator:
  - name: common-env-config
    envs:
      - ../../../config/common-env.env
