---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: longhorn
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m0s
  install:
    createNamespace: true
  values:
    preUpgradeChecker:
      jobEnabled: false
    longhornUI:
      replicas: 1
    service:
      ui:
        type: ClusterIP
        annotations:
          glance/name: "Longhorn"
          glance/icon: "si:longhorn"
          glance/url: "https://longhorn.home.coredev.uk"
          glance/description: "Storage Management"
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.home.coredev.uk
      tls: true
      tlsSecret: longhorn-tls
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia-forwardauth@kubernetescrd
    defaultSettings:
      defaultReplicaCount: "1"
      storageOverProvisioningPercentage: "200"
      storageMinimalAvailablePercentage: "10"
      defaultDataLocality: "best-effort"
      backupTarget: "nfs://192.168.20.40:/var/nfs/shared/LonghornBackups?nfsOptions=vers=3,hard,timeo=600,retrans=3"
      backupTargetCredentialSecret: ""
