apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: notifiarr
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 2m
  path: ./k8s/notifiarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: longhorn
    - name: authelia
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  timeout: 5m
