apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: notifiarr

resources:
  - ingress.yaml
  - deployment.yaml

configMapGenerator:
  - name: common-env-config
    envs:
      - ../../../config/common-env.env
