apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-secrets
    namespace: notifiarr
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:rJwDSFRcIvCE3Jep9193TCI9o8iE3rgiyEumrxgSOZfYqKz8,iv:TjWkVV+E7PKwzlfweqnwUrQvylR9O8n9eXV0jLKees8=,tag:B6EwwSNaf5SJIKzjRJB4eA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUXBVU3EwY25RWXJVVU9Z
            b0ppUkhZSEVVMUVCMmpqSHBUN2xIaGZjeTBZCldobmZqak5LT0NMZTcrVXh6K2d0
            cThOUGR1Ri9DNExxQWg0NFdBbUtTMTgKLS0tIHN5aEw1aG5Hd2xvL0JZZkZ3T1RE
            U0dLM2NpQy9oMlNlR2V5TC9iSG9iSm8Kk++Sf2ZPq/wg25tRdjaZktyBfLwSIgxd
            lh7Q64L12+xFxlZOZzx8EAtbezecVvHPr5QIX9vdTSzpWngF5xA/6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:40:27Z"
    mac: ENC[AES256_GCM,data:uP+I6kCy44o27+byksZfeHdQzvkMI9T7lIhblwW0f2seJV8bbqrS9T07Q4Qbkrw1gK6K3nySj5vfo6/IRhd1QGxOUO8d5f4oRHS8Zbai2MWvcFhgD8pRtbyxgSwdHSt3EPrxXaOcJRegRVYG4gFX4TU9jmUTpYAxfsAfF8TSo2A=,iv:Hiyv26XGrFfSvIXU6505hz1YI0JwWvKwpNXCwgv8+/o=,tag:n4zeOzyIQfBHnYpd5egqUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
