---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: anza-labs
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://anza-labs.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: flux-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: pocket-id
      version: 1.7.3
      sourceRef:
        kind: HelmRepository
        name: anza-labs
        namespace: flux-system
      interval: 1m0s
  targetNamespace: pocket-id
  valuesFrom:
    - kind: ConfigMap
      name: pocket-id-values
      valuesKey: values.yaml
