apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
  - ingress.yaml

configMapGenerator:
  - name: pocket-id-values
    namespace: pocket-id
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
