replicaCount: 1

timeZone: "Europe/London"
analyticsDisabled: true

host: "pocket-id.home.coredev.uk"

database:
  provider: "sqlite"
  connectionString: "file:data/pocket-id.db?_pragma=journal_mode(WAL)&_pragma=busy_timeout(2500)&_txlock=immediate"

pocketID:
  image:
    repository: ghcr.io/pocket-id/pocket-id
    tag: "v1.16.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

config:
  create: true
  ui:
    useDefaults: false
    settings:
      app:
        appName: "Homelab ID"
        sessionDuration: 720
        emailsVerified: true
        allowOwnAccountEdit: true
        disableAnimations: false

persistence:
  data:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

podAnnotations:
  glance/name: "Pocket ID"
  glance/icon: "si:openid"
  glance/url: "https://pocket-id.home.coredev.uk"
  glance/description: "Identity Provider"
