# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/service.json
apiVersion: v1
kind: Service
metadata:
  name: frigate-exporter
  namespace: frigate
  labels:
    app: frigate-exporter
spec:
  ports:
    - port: 9100
      targetPort: 9100
      name: frigate-metrics
  selector:
    app: frigate-exporter
