apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mediamanager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/mediamanager
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: longhorn
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  timeout: 10m
