apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homebridge
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 2m
  path: ./k8s/homebridge
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
  wait: true
  timeout: 5m
