apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
  - controller.yaml

labels:
  - pairs:
      app.kubernetes.io/name: sealed-secrets
      app.kubernetes.io/component: controller
