apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-storage
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 2m
  path: ./k8s/shared-storage
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  wait: true
  timeout: 5m
