apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app/

configMapGenerator:
  - name: traefik-values
    namespace: flux-system
    files:
      - values.yaml=app/values.yaml

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
