apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: headscale
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s/headscale
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: longhorn
    - name: wireguard-client
    - name: pocket-id
