apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pocket-id
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/pocket-id
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: longhorn
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: pocket-id
      namespace: pocket-id
    - apiVersion: apps/v1
      kind: Deployment
      name: tinyauth
      namespace: pocket-id
