apiVersion: v1
kind: Secret
metadata:
    name: qui-oidc-secret
    namespace: qbittorrent
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:1OdwyEGVJgcFk6O6Nti8rG3n6mCxT2aFrFfIMerVKxbj02rBoCfQ21MZW5lVPUCBCgVvK1uL8vlegDRZ,iv:VPm3sLUi0nn1FjfInhwPWlFWUdJPHwQRQqnkCx2+z4Y=,tag:KNzUjZ/a9JUWhTzmXbxLig==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdWIvWkRrRlZsME5FM1NF
            R0RGaFB0L2YzOU1HNmdvUXpyYitTSTFLaFZJCnpqV3ZISmNtVlBZeXJ6dkJXVHZQ
            WjE2NWNYMDNsS3BjaEVDOUJEUjNXajgKLS0tIC9FSU00RmplMWRUWFlMb0xXRkMx
            UFMxeEpBM2dIWGc0bDVjclo0a3RFTGcKplctG71AmpqsQtejEWWSMEcJJ8YDI4uV
            7XLTQTKuDFfPOvVdY34CfoRlBsieh1yfScCz8SfzM2JXw6+pDaAHwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:37:39Z"
    mac: ENC[AES256_GCM,data:Vbg1Nj4ZjbJxKdB8Otc2YUr6i7OsJjTw8YfuS/p+lrderA3w5uVG+S5EkOwISQIHnxNxapBhYt7eO2qIutnUMkYmPcaYizHeDloNT5cwXXVMdSPAlu/CAluQGQFIrMBXKlMJSXCiS+Ap6rGt2SkcDSsPt6EmXGZ6DJughVbjOWQ=,iv:c2it/j2mKYQXSah9ATSfIoA8b7UUnR27Z9CfM6Eh3v8=,tag:MHszx3y7+BVR4tMwiSTEOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
