apiVersion: v1
kind: Secret
metadata:
    name: vpn-secrets
    namespace: qbittorrent
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:u5UNtqx9VPiekhyLdwNwiff9R5NATyH77oYi2j8ed9MJ5+a4hZpGKUERdIo=,iv:LV71fQHfKK+xVq09NxAIo8tNNRW54T53BgXrAATFrjM=,tag:x/KfH7yONP2JEtSGiGA9fA==,type:str]
    proton-email: ENC[AES256_GCM,data:epaFr6TASHzq+GfJuCDPrJrMbcBQY6TjYw==,iv:urqdmxHZVsasouf2Iog+ffD52wdafdg4/oYEJSuxJhc=,tag:1cPZ3Krm/idial6ppgyMsw==,type:str]
    proton-password: ENC[AES256_GCM,data:t27m2VDHISrEnVS4NhUuQMxnycTtd9fE/PBEaIrFztg=,iv:W1gjHu9824D2bPQ4q9DvgyLwV98vA5kFKZzTZhmYMmc=,tag:LcmR5+EsgDacnaqkEA7HeA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYlYyUE1Pa2lERWgzcVk0
            MEl1QllXNHl2U0doNDBqQ1N1SG5XTjBubDJFCmZsMUFLbDRiS0tjVnBVNm94UzlJ
            Wlp2bDdKcVREb05FeGdxb1FJYVZ2YVEKLS0tIC9JbUtmM25pVlYxTUYrMVFReTVP
            YWdoaWRKTG5uREhwMTdZUDVSTjRSMW8KSa29iDCpRe9XA+RHjCUaluFvXEQaM6wR
            H9eKYtVfFGM49FNRt+OfzRioiLoN0YQp5kT9wyAyG8V6Q7Gaxe4RkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T21:41:00Z"
    mac: ENC[AES256_GCM,data:wJq0lm2oYtGk73APahvfbo1CCYWxE7t5m/m5TUq4nxx+sSWr3Jc654mhbAUAwVHNBPO2wUelD/hgZY547i5SSxHW3jw853AyfTNDxJZ2CLCSvNKpjA/+3vQnAw9sFzLdEkikoaX8zWh7wbyEMfQUauuoqWKRxb8syPgqQ5JEqac=,iv:XjOjM+R3Gamf6ZWSOKlWGZmoEPnHdEIA3OZvwggrpR0=,tag:Qoj+E6F1tbcj4u1uOll5LQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
