apiVersion: v1
kind: Secret
metadata:
    name: vpn-config
    namespace: qbittorrent
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:gQQEDnOg8Pxqwgqboc8lJOiVOho6p7WuZ0FlKWiEFIXOrbu8KgUluJURP6Q=,iv:KZSYbGUhKdQMPyYTDQtK99yZUJBhGlVv9jFUimk31lo=,tag:mPhZwalpDjLrbGDWhz9twA==,type:str]
    proton-email: ENC[AES256_GCM,data:3JTX4z1n/FYQSBLWuagP2uscaWcvuHB5Yw==,iv:M07uJTlXYMhNlFkdmV6C4he2/EhP2xGifkP2TpLc9fk=,tag:1ozKPlMwPhVopkaPCJjzIQ==,type:str]
    proton-password: ENC[AES256_GCM,data:zmKXuh8OEg1veD6lchs3Cgkv4hLlq58UGpo+rFpOsUo=,iv:RSorOvAY6QAqYMJNt6bYSzZlpgDmoLtoXksBYRp8F6o=,tag:IFvG3ops9kRJgS0Vtcq/Pg==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNUVCN2p4VitmRmZaazcz
            ODEyUjc3cHcxd29TSXMySWV3Rm1TWVg5Slh3CjJSSW11VGlHVmJwSW5vbzlsbUtD
            ZHFUOWtYUHl1OG83V2VyL0tUbTZPcmsKLS0tIER6RHZyMGNDYTVTUG5wVWNBa3N2
            aGhrR3FRWkREeUI1T2dBTXVBZ0szdDgKzOw05w5wTysk4TWBmO1lSVifrMWCg9BI
            yVX+vnhZolaSBaCvwf6VCLY+nzWxT7GiJwLze41F+hzVcv1FgFuoTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T12:40:29Z"
    mac: ENC[AES256_GCM,data:9BjUHZqLUSJvYcdRsgLTO7+/68hTSUdvtgPKnI47IdS3I2zBg7PH84ndVnHasx8kzTT4Mp+NlEP8wLEzjsC+EaqsRwr5VyKc1R3oH/O0Pqh1kn3Vb1y5bZjtd8aQcAj9QE6a3vv2Ed7ddZoR+fQdbdC1LUjrC0bs6mDDoyHJNnU=,iv:A2QWcgJSsGtfuCJ3pGWa5uicoTmycT2huP+UAeQLzfY=,tag:Tl/vLpXei5xfhw2OUIKJrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
