apiVersion: v1
kind: Secret
metadata:
    name: vpn-secrets
    namespace: qbittorrent
type: Opaque
stringData:
    private-key: ENC[AES256_GCM,data:2xvLkddGSFaJOE5sSGqwXQ3r82l5EB41SlRjr0TRUEyQJJK8DU/fnSEw7xc=,iv:Qo/FXVUFRN+HvxhZ05NFPE0Q3wMbbUN3tChJAas3V6k=,tag:ZF/9FwHS9nn9JDxFJm/3kw==,type:str]
    proton-email: ENC[AES256_GCM,data:epaFr6TASHzq+GfJuCDPrJrMbcBQY6TjYw==,iv:urqdmxHZVsasouf2Iog+ffD52wdafdg4/oYEJSuxJhc=,tag:1cPZ3Krm/idial6ppgyMsw==,type:str]
    proton-password: ENC[AES256_GCM,data:t27m2VDHISrEnVS4NhUuQMxnycTtd9fE/PBEaIrFztg=,iv:W1gjHu9824D2bPQ4q9DvgyLwV98vA5kFKZzTZhmYMmc=,tag:LcmR5+EsgDacnaqkEA7HeA==,type:str]
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYlYyUE1Pa2lERWgzcVk0
            MEl1QllXNHl2U0doNDBqQ1N1SG5XTjBubDJFCmZsMUFLbDRiS0tjVnBVNm94UzlJ
            Wlp2bDdKcVREb05FeGdxb1FJYVZ2YVEKLS0tIC9JbUtmM25pVlYxTUYrMVFReTVP
            YWdoaWRKTG5uREhwMTdZUDVSTjRSMW8KSa29iDCpRe9XA+RHjCUaluFvXEQaM6wR
            H9eKYtVfFGM49FNRt+OfzRioiLoN0YQp5kT9wyAyG8V6Q7Gaxe4RkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T15:36:06Z"
    mac: ENC[AES256_GCM,data:mQYEY6hwCXZFugQ4RcNT5soBzaF2hNMthiZ13PnigqBEgKdvUua/RqBQiVKiTagtxA52LXGtzzgXgpLhLqNrfbuBTNB2uetpAX4ssGwLLD7XlIpxdLLnB8PfZNCSWroGNmEv/Jiw5JpL91i5MmPUoqYDdyqWKkeSDo4/Wc4aZpo=,iv:M1ry34vRFZDb8WWGeCDgxP/M4wLawyxYb1M7mydPykQ=,tag:7R+cu8vkaQXKmsPh0gMm6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
