# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://github.com/seerr-team/seerr
  ref:
    branch: develop
  ignore: |
    /*
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: flux-system
  annotations:
    glance/name: "Seerr"
    glance/icon: "di:jellyseerr"
    glance/url: "https://seerr.home.coredev.uk"
    glance/description: "Media Requests"
spec:
  interval: 10m0s
  timeout: 5m
  chart:
    spec:
      chart: ./charts/seerr-chart
      sourceRef:
        kind: GitRepository
        name: seerr
        namespace: flux-system
      interval: 1m0s
  targetNamespace: seerr
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: seerr-values
      valuesKey: values.yaml
