---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seerr
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/seerr-team/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: flux-system
  annotations:
    glance/name: "Seerr"
    glance/icon: "di:jellyseerr"
    glance/url: "https://seerr.home.coredev.uk"
    glance/description: "Media Requests"
spec:
  interval: 10m0s
  timeout: 5m
  chart:
    spec:
      chart: seerr-chart
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: seerr
        namespace: flux-system
      interval: 1m0s
  targetNamespace: seerr
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: seerr-values
      valuesKey: values.yaml
