apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyseerr
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/jellyseerr
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  dependsOn:
    - name: traefik
    - name: longhorn
    - name: jellyfin
    - name: radarr
    - name: sonarr
  wait: true
  timeout: 5m
