apiVersion: v1
data:
    authkey: ENC[AES256_GCM,data:Le9DjK8CPlqr6msdZu6C4xC5Ijg0ssgCsNXunxyb+pXPWbjycuRIlz+PrP17KhHmPg5H4CeG6cxCZrep,iv:HfKXauB3GkjFmwzEE4W+e9f4cS9M7upXageoSeAN0vY=,tag:IRCj8CuOwKA5E3yQJmPjNw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tailscale-auth
    namespace: tailscale-router
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TEpLQXUrSEhSTzVYRjFG
            c0tHcG14T2UvNk9Qd3JCLzRGZEZuWms1YUVrClJCV0J5WkZEb0N6dDgrQXcxN0Vr
            ZzQyS2EyUExmNnZWOG1rQmhuMVRnTFEKLS0tIG80Z3JSQktkbjBBU3hxcmtwZGky
            OHF2Nm1adGZQcG1NMDd1VmdSUEh3U1kK7sxBf+58klV4cpQ/OO77Z0Y4+zDKbXVm
            Q05EhXIHvmBbRQmGQxL1sGNXltUur3X2AxRSWo8B4Lmkz++bCgCUWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:32:44Z"
    mac: ENC[AES256_GCM,data:WfpikCSpiCkQ9KauPxUWnA4eoLMWPC4+h9JDZT7sbhFpRNW3z6I/pydJIv0dP8XoguWxiBUUBqc7fb82YtZWLC5K30gjZk9XAvTtcWl57N9lnCpsPbkh4LIdxs+BVcOj9bnLnp/wVayHoBw5Mz96OLKf6Bcflc6MtB9aZj+TzwI=,iv:qpo/NdTmQjl0uBHyCczCS3FUD22Gj0m7X5wIqmxN2PE=,tag:ntLplajudvUjUVTcKlW6fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
