apiVersion: v1
data:
    authkey: ENC[AES256_GCM,data:EyAAjeycBM/O5ADGEJpPE4SKoPQWNsi1Lar4ypwlfaZKcRqWE8Ripi2HyGl7V8rFZBkxVKPelzYr6YQYDhlhDg==,iv:91De474BdNN3Y89af8RoAUSB79LVbPOeVLlTheFoNRA=,tag:XZEC4F9ZQDYqucGGIp9/3A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tailscale-auth
    namespace: tailscale-router
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOVREVWNhUlJKNXh3aldJ
            c2t2aDdjNm1YYWNqbHVPM0RLeURKRnZQbGo4CisxRXB2TFYybXVmM3dSMkVPa2p0
            RzRzMlBkci93dFNLYTF5V0lPUWg5eVUKLS0tIEk3UU5aU3NCYVk1ZHQyTFBwR2RP
            MTlpOGppdXVFNmFZQkdSdW1Od0FrdDgKf11PlmDJLi3G4hf1dGWAFx2A5EI9kfj2
            WyqSM9GO3uS8KYUktbKcKRyPvqR+CNYcWQqScDgrktCGwumcaonW2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T18:00:25Z"
    mac: ENC[AES256_GCM,data:QxjW0WHDk1SL6tGMaNXM1EVIJazf52Va3AULeuNj8+2VQhejIj0n8H0ERz5anGsiMeJFeF3NWDYOzhpX1N0ca71IjU8lefElB2NiTgOyC91XioDrK8Bla8oYBYSqwooXiKhWJJpF0tUg++C0BGhW6fu24sAmRgv97PZZrU25iEw=,iv:ApDmcgMwLnARX7DuM471SFW6KB4x7p0aV1Uzir+/QK4=,tag:3SOaaK7S3lTgGtVvmaHtKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
