apiVersion: v1
data:
    authkey: ENC[AES256_GCM,data:Wob5BAhAZUzaDqOV2noeLFwI1FB/3tGpB0fymJ2/M5uiY5OYtjeSclkD9fMd+6m7sUAEMCmmsUPQ/x7O6LJKYQ==,iv:p0HskB2eorN3nk2b7PFtfAuO8lSrPAVStvHtAzdBLHU=,tag:tj90W+C93YBr7g+ldFk92w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tailscale-auth
    namespace: tailscale-router
sops:
    age:
        - recipient: age14vtdunml8z4k3y0k2jrrutkf65rntqdsye83awyzm87ur5gw2pts3wkw3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MFF5UXJ0Um5wc3pKRkt0
            WWxLMmpGUFQ2SExIeWduZGNwTmhYWFhIRFR3CjF1d2YrUzAvNDh2VEJSeTVIMTZC
            WGhldjVUOTNPSjNrRlB6U2dMZE5TbnMKLS0tIE1UamYxQlYxZkIyd1BGSm1DQ3Ri
            QlM0V1Q3TFdvY2dwdTNBSDR2ek0wbkEK3+u6WoEVRMD4IVSpr9AQoYj1FWRZm6sS
            gIukYLFLJaMDp/BuQeNUDw3tPGDn7G4eAmgOYmCa4qDOpbR+GPI/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T17:44:38Z"
    mac: ENC[AES256_GCM,data:bOOQVXXOTYb7y8L+3qoafo4ZgJkcDHtGQNasv2szHeprTEvOiOvXuKyinYZvGaZV5R5yd82J6Fuf6OM1NOqNNhkTAy53dveDyECDZ+j/UH/k7yjGf7CNho6WFzH7lq1LcJsE+Qvhdhmac2oAf+el4gPwiuRvu43s7UGP/LRUDx8=,iv:DPaNUlVmdj6iiXft68tIJC3TuQSAhex/P/NhGytJPLs=,tag:T9UnANAH0B5Mrjs9jB04KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
