---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/vector
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 5m
  wait: true
