server:
  host: 0.0.0.0
  port: 3000
  base_url: https://headplane.home.coredev.uk
  cookie_secret: placeholder-will-be-overridden-by-env
  cookie_secure: true

headscale:
  url: http://headscale.headscale.svc.cluster.local:8080
  config_path: /etc/headscale/config.yaml
  config_strict: true

oidc:
  issuer: https://oidc.coredev.uk
  client_id: placeholder-will-be-overridden-by-env
  client_secret: placeholder-will-be-overridden-by-env
  headscale_api_key: placeholder-will-be-overridden-by-env
  token_endpoint_auth_method: client_secret_post
  disable_api_key_login: true
