apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headplane-ingressroute
  namespace: headscale
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headplane.home.coredev.uk`) && PathPrefix(`/admin`)
      kind: Rule
      services:
        - name: headplane
          port: 3000
    - match: Host(`headplane.home.coredev.uk`) && Path(`/`)
      kind: Rule
      middlewares:
        - name: headplane-admin-redirect
          namespace: headscale
      services:
        - name: headplane
          port: 3000
  tls:
    secretName: headplane-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headplane-redirect
  namespace: headscale
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`headplane.home.coredev.uk`)
      kind: Rule
      middlewares:
        - name: https-redirect
          namespace: traefik
      services:
        - name: headplane
          port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: headscale
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headplane-admin-redirect
  namespace: headscale
spec:
  redirectRegex:
    regex: ^https://headplane\.home\.coredev\.uk/$
    replacement: https://headplane.home.coredev.uk/admin
    permanent: false
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headplane-tls
  namespace: headscale
spec:
  secretName: headplane-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - headplane.home.coredev.uk
