apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm.yaml

configMapGenerator:
  - name: pihole-values
    namespace: flux-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
